<div id="content-978"> 
        
        
       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a></div>

            <div class="top-left"><span>Le Fan Club</span><p> </p></div>
        	</div>
           
           
            <div id="services-978">
            
            <div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/19110nscription_connexion.jpg" width="623" height="400"></div></div>
           <div id="services-978">
           <div class="services-title-blue">VOS AVANTAGES FAN CLUB</div>
           
           <div class="services-978"><strong><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/serv1.png" width="651" height="162"></div><br>
           Vous bénéficiez des PRIX Fan*, - 5% de réduction immédiate sur tous les articles signalés de l&rsquo;équipement du pilote et de la moto en <a href="http://www.motoexpert.fr/fr/magasins/">MAGASIN</a><br>
             Vous pouvez cumuler plusieurs produits à PRIX Fan* à chaque achat.</strong>
             
             <center><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/0_19149.png" width="577" height="229"></div></center>
           
           </div>
          
         <div id="services-978">
           
           
           <div class="services-978"><strong><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/jack.png" width="651" height="162"></div></strong>
             <p><strong>Nous versons 3% du montant de vos achats sur votre compte Jackpot!, disponible dès votre prochain achat en <a href="http://www.motoexpert.fr/fr/magasins/">MAGASIN</a></strong></p>
             <p><strong>Le solde du compte Jackpot est valable 6 mois à partir du dernier achat cumulé.</strong></p>
             <center><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/did.png" width="555" height="316"></div></center>
           </div>
           

          </div>
          
          
          <div id="services-978">
            <div class="services-978"><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/coment.png" width="651" height="114"></div><br>
             Dans votre <a href="http://www.motoexpert.fr/fr/magasins/">MAGASIN</a> Moto Expert :<br>
            Demandez à rejoindre le FAN CLUB <em><strong>gratuitement</strong></em> et <strong><em>profitez immédiatement du</em>PRIX Fan*, <em>du </em>Jackpot!* <em>et de tous les privilèges</em>.</strong></div>
           

          </div>
          
          <div id="services-978">
            <div class="services-978">* Offre valable sur l&rsquo;équipement du pilote et de la moto signalée par la réduction « Prix FAN » et « Jackpot! », réservée aux membres du FAN CLUB dont l&rsquo;adhésion est GRATUITE. Hors motos d&rsquo;occasion, pneumatiques, service rapide, promotions et soldes. Dans tous les magasins Moto Expert participant au programme de fidélité, liste disponible sur <a href="http://www.motoexpert.fr/">motoexpert.fr</a>. Voir conditions en magasin. Moto Expert se réserve le droit de modifier son programme de fidélité à tout moment. Affiliation CNIL : 148 32 51.</div>
           

          </div>
          

       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a><p>&nbsp;</p> 
           	</div>
       	    </div>    
          
    </div>      
        <div id="footer">
        	<div class="footer-logo"><img src="<?php echo MEDIA_URL ?>images/footer-logo.png" width="264" height="97" /></div>
            <div class="footer-col1">
              <a href="#">DÉPOSEZ VOTRE ANNONCE GRATUITE</a></p>
              <a href="#">MOTOS D’OCCASIONS</a></p>
            </div>
          <div class="footer-col2">
	          <h3>LES SERVICES MOTO EXPERT</h3>
              <form id="form3" name="form3" method="post" action="">
                                <label for="select"></label>
                                <select name="select" id="select">
                                	<option value="0" selected="selected">Ville</option>
                                    <option value="1">Ville 1</option>
                                    <option value="2">Ville 2</option>
                                    <option value="3">Ville 3</option>
                                    <option value="4">Ville 4</option>
                                    <option value="5">Ville 5</option>
                                    <option value="6">Ville 6</option>
                                </select> 
                                <input type="submit" name="button" id="button" value="" />
                              </form>
              
          </div>
          <div class="footer-col3">
          	<h3>LES SERVICES MOTO EXPERT</h3>
              <a href="#">Occasion moto</a>
              <a href="#">Service rapide</a>
              <a href="#">Fan Club</a>
          </div>
          <div class="footer-col4">
          	<a href="#">L’ACTU</a>
            <a href="#">CONTACTS</a>         
          </div>
          
          <div class="copy">© 2014 MOTOEXPERT   Réalisation : Infra - Tous droits réservé</div>
        </div>
	</div>