<div id="content-978"> 
        
        
       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a></div>

            <div class="top-left"><span>Le Fan Club</span><p> </p></div>
        	</div>
                <?php
                 $config = Zend_Registry::get('config');
                 $ruta = $config->app->photoNews;
                ?>
           
            <div id="services-978">
            
            <div class="fan-service"><img src="<?= $ruta.$this->fan[0]['value'];?>" width="623" height="400"></div></div>
           <div id="services-978">
           <div class="services-title-blue"><?= $this->fan[2]['value'];?></div>
           
           <div class="services-978">
               <strong>
                   <div class="fan-service">
                       <img src="<?php echo MEDIA_URL ?>images/services/serv1.png" width="651" height="162">
                   </div>
                   <br>
                   <?= $this->fan[6]['value'];?>
            </strong>
             
             <center><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/0_19149.png" width="577" height="229"></div></center>
           
           </div>
          
         <div id="services-978">
           
           
           <div class="services-978"><strong><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/jack.png" width="651" height="162"></div></strong>
             <p><strong>Nous versons 3% du montant de vos achats sur votre compte Jackpot!, disponible dès votre prochain achat en <a href="http://www.motoexpert.fr/fr/magasins/">MAGASIN</a></strong></p>
             <p><strong>Le solde du compte Jackpot est valable 6 mois à partir du dernier achat cumulé.</strong></p>
             <center><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/did.png" width="555" height="316"></div></center>
           </div>
           

          </div>
          
          
          <div id="services-978">
            <div class="services-978"><div class="fan-service"><img src="<?php echo MEDIA_URL ?>images/services/coment.png" width="651" height="114"></div><br>
             Dans votre <a href="http://www.motoexpert.fr/fr/magasins/">MAGASIN</a> Moto Expert :<br>
            Demandez à rejoindre le FAN CLUB <em><strong>gratuitement</strong></em> et <strong><em>profitez immédiatement du</em>PRIX Fan*, <em>du </em>Jackpot!* <em>et de tous les privilèges</em>.</strong></div>
           

          </div>
          
          <div id="services-978">
            <div class="services-978">
                <?=$this->fan[3]['value'];?>
            </div>
           

          </div>
          

       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a><p>&nbsp;</p> 
           	</div>
       	    </div>    
          
    </div>      
        
	</div>