<div id="content-serp28"> 
        	<div id="content-top">
            
                            <div class="top-left"><span>FRANCHISE ET SERVICES</span></div>
        	</div>
           
           
            <div id="services">
            
            	<div class="services-subtitle">Moto Expert est le spécialiste de l’équipement du pilote et de la moto, du dépôt-vente  et de l’achat cash de motos d’occasion, du service rapide.<br>
              Moto Expert, pour simplifier la vie des motards, assurer votre confort et votre sécurité.</div>
              	
                	<div class="services-block">
                    	<div class="services-img"><img src="<?php echo MEDIA_URL ?>images/service1.jpg" width="265" ></div>
                        <div class="services-text">
                        	
                        
                          <div class="services-title-blue">OCCASION MOTO</div>
						  <div class="services-text-content">Au cœur de toutes les tentations, la moto d’occasion est largement exposée au centre de nos magasins. Vous trouverez forcément votre moto chez Moto Expert, 1er réseau Français de vente de moto d’occasion.
Que vous soyez acheteur ou vendeur, nous nous occupons de tout !</div>
<div class="services-btn">
	<a href="occasion-moto.html" class="btn-savoir">EN SAVOIR PLUS</a>
</div>


                      </div>
                    </div>
                    
                    
                    <div class="services-block">
                    	<div class="services-img"><img src="<?php echo MEDIA_URL ?>images/service2.jpg" width="265" ></div>
                        <div class="services-text">
                        	
                        
                            <div class="services-title-blue">FAN CLUB</div>
							<div class="services-text-content">Découvrez tous les avantages de la carte de fidélité Moto Expert<br>
							  Elle vous permet de bénéficier de réductions immédiates sur tous les articles signalés de l’équipement du pilote et de la moto en MAGASIN...<br>
						    ... et nous vous versons un pourcentage de vos achats sur votre compte JackPot.</div>
<div class="services-btn">
	<a href="carte-fidelite.html" class="btn-savoir">EN SAVOIR PLUS</a>
</div>


                      </div>
                    </div>
                    
                    
              <div class="services-block">
                    	<div class="services-img"><img src="<?php echo MEDIA_URL ?>images/service3.jpg" width="265"></div>
                        <div class="services-text">
                        	
                        
                            <div class="services-title-blue">SERVICE RAPIDE</div>
							<div class="services-text-content">Qaulité, Prix, délais... plus de 75 préstations pour l’entretien de votre moto.</div>
<div class="services-btn">
	<a href="service-rapide.html" class="btn-savoir">EN SAVOIR PLUS</a>
</div>


                      </div>
                    </div>
                    
                    <div class="services-block">
                    	<div class="services-img"><img src="<?php echo MEDIA_URL ?>images/libvra.png" width="265"></div>
                        <div class="services-text">
                        	
                        
                            <div class="services-title-blue">LE SERVICE LIVRAISON</div>
							<div class="services-text-content">Vous avez enfin trouvé votre moto dans le réseau Moto Expert et elle se trouve à plusieurs centaines de kilomètres ?</div>
<div class="services-btn">
	<a href="livraison-moto.html" class="btn-savoir">EN SAVOIR PLUS</a>
</div>


                      </div>
                    </div>
                    
                    
          </div>
          
          
          
          
          

          
          
    </div>