<div id="content-978"> 
        
        
       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a></div>

            <div class="top-left"><span>LE SERVICE LIVRAISON</span>
                         <p>&nbsp; </p>
                         
            </div>
        	</div>
       	  <div id="services-978">
           <div class="services-title-blue">LIVRAISON PARTOUT EN FRANCE</div>
           
           <div class="services-978">
           
           <div class="services-imglir"><img src="<?php echo MEDIA_URL ?>images/services/libvra.png" width="243" height="170"></div>
           
       
             <strong>Vous avez enfin trouvé votre moto dans le réseau Moto Expert et elle se trouve à plusieurs centaines de kilomètres ?

Nous avons la solution, faites vous livrer votre moto dans le magasin Moto Expert le plus proche de chez vous partout en France !</strong><br>
<br>
 <br>
<br>
  <p>La livraison simple et rapide,</p>
               <strong><br>
               1. Prenez contact</strong> avec le magasin Moto Expert vendeur de la moto d&rsquo;occasion<br>
                 <strong>2.</strong> Il vous informera du <strong>prix, du délai et du lieu de livraison</strong><br>
                 <strong>3.</strong> Pour <strong>confirmer la livraison</strong>, envoyer le règlement au magasin Moto Expert expéditeur.<br>
                 <br>
                 <strong>Faites-vous livrer en toute sécurité,</strong><br>
                 Avec notre partenaire Distri Byke, profitez d&rsquo;une livraison en toute sécurité<br>
                 N°1 en France en matière de transport de motos et quads<br>
                 Transport de votre moto avec des solutions adaptées et brevetées<br>
                 <br>
                 <strong>Des tarifs clairs,</strong><br>
                 Un tarif livraison régionale(1)<br>
                 Un tarif livraison nationale(1)<br>
                 <br>
                 (1)hors quad et motos volumineuses type Goldwing et surtaxe gazole
            
            <br>
           </div>
           

          </div>

          <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a><p>&nbsp;</p> 
               	</div>
       	    </div>    
          
    </div>