<div id="content-978"> 
        
        
       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a></div>

            <div class="top-left"><span>OCCASION MOTO</span>
                         <p>&nbsp; </p>
                         
            </div>
        	</div>
           
           
            <div id="services-978"> <div class="services-978">
            Au cœur de toutes les tentations, la moto d’occasion est largement exposée au centre de nos magasins. Vous trouverez forcément votre moto chez Moto Expert, 1er réseau Français de vente de moto d’occasion.

Que vous soyez acheteur ou vendeur, nous nous occupons de tout !          <br>
<br>
<div class="services-imglir img100">
<img src="<?php echo MEDIA_URL ?>images/services/solutions.png" width="625" height="90">
</div><br><br>

<br>

<strong><br>
Vous êtes vendeur ?<br>
Nous vous proposons 3 solutions pour vendre vite et bien votre moto :</strong>            </div>
          </div><div id="services-978">
           <div class="services-title-blue">MOTO EXPERT ACHÈTE CASH VOTRE MOTO(1)</div>
           
           <div class="services-978"><div class="services-265"><img src="<?php echo MEDIA_URL ?>images/services/moto.jpg" width="250" height="175"></div><p><strong>La solution simple et rapide !</strong></p>
           <br>
        
             <strong>1. Rendez-vous dans votre magasin</strong> <strong>Moto Expert </strong>avec votre moto, son trousseau (carnet d&rsquo;entretien, factures, double de clés, accessoires, pièces d&rsquo;origine…) et le certificat de non-gage. <br>
               <br>
               <strong>2. Nous définissons le prix d&rsquo;achat</strong> après expertise de votre moto et selon plusieurs critères, la marque, le modèle, l&rsquo;année, le kilométrage, l&rsquo;état, votre estimation, la cote professionnelle, les réalités marchandes, le positionnement de la moto sur le marché de l&rsquo;occasion.<br>
               <br>
               <strong>3. Dès l&rsquo;accord trouvé</strong> par les deux parties, nous remplissons les formalités administratives et vous recevez immédiatement le paiement !<br>
               <br>
               <strong>4. Dans le cadre d&rsquo;une reprise</strong>, essayez et choisissez votre future moto. Nous vous proposons une offre de reprise, elle est sans engagement de votre part : si vous ne voulez pas racheter de moto, repartez simplement avec votre chèque !
           
         
               <br>
               <br>
             (1) Nous nous refusons l&rsquo;achat d&rsquo;un véhicule qui ne correspond pas à nos critères.<br>
                 L&rsquo;achat cash est une offre valable uniquement dans les magasins participants.
         
           </div>
           
           </div>
          
         <div id="services-978">
           <div class="services-title-blue">LE DÉPÔT-VENTE</div>
           
           <div class="services-978"><div class="services-imglir"><img src="<?php echo MEDIA_URL ?>images/services/deport.jpg" width="249" height="256"></div>
             <p><strong>Gratuit jusqu’à la vente de votre moto !</strong></p>
             <br>
             <br>
          
              <strong>1. Rendez-vous dans votre magasin Moto Expert</strong> avec votre moto, son trousseau (carnet d&rsquo;entretien, factures, contrat d&rsquo;assurance, double de clés, accessoires, pièces d&rsquo;origine…) et le certificat de non-gage.<br>
                 Nous expertisons votre moto, nous la testons et évaluons son état.<br>
                 Nous fixons ensemble le meilleur prix de vente adapté aux réalités marchandes.<br>
                 Nous <strong><a href="http://www.motoexpert.fr/fr/services/occasion_moto/achat.php">garantissons votre moto</a></strong> selon des critères définis<br>
                 Nous établissons votre contrat de dépôt vente.
       
             <br>
             <br>
               <br>
             
                 <strong>2. Nous exposons et vendons votre moto</strong><br>
                   Au cœur du magasin Moto Expert, votre moto est mise en valeur sur un espace dédié et sécurisé. <br>
                   Sur www.motoexpert.fr, elle est exposée à des millions d&rsquo;internautes et sur nos sites partenaires 7 jours/7 et 24h/24.
               
               <br>
               <div>
                 <div>
                   <strong>80% des motos qui nous sont confiées sont vendues dans les 2 mois.</strong><br>
                     <br><div class="services-imglir img100"><img src="<?php echo MEDIA_URL ?>images/services/trafict.jpg" width="388" height="200"></div>
                     <strong>3. A la vente de votre moto</strong>, nous vous appelons et vous proposons un rendez-vous pour retirer le paiement de votre moto.<br>
                   Si votre moto n&rsquo;est pas vendue dans les 2 mois, venez la récupérer ou renouvelez le contrat, dans les 2 cas, vous ne payez rien !
                 </div>
               </div>
           </div>
           

          </div>
          
          
          <div id="services-978">
           <div class="services-title-blue">LE SITE MOTOEXPERT.FR</div>
           
           <div class="services-978"><div class="services-imglil"><img src="<?php echo MEDIA_URL ?>images/services/votre.jpg" width="250" height="216"></div>
             
                 <p><strong>Vous voulez vendre votre moto rapidement, en toute simplicité et sans vous déplacer ? Passez une annonce sur www.motoexpert.fr, c&rsquo;est 100% efficace et 100% gratuit !</strong><br>
                 </p><br>
                   <br>
                   <strong>1. Créer votre compte</strong> ou identifiez vous,<br>
                   J&rsquo;accède à la rubrique « <strong><a href="http://www.motoexpert.fr/compte/identification/identification.php">Mon compte</a></strong> »<br>
                   <br>
                   <strong>2. Déposez votre annonce</strong> parmi plus de 2500 annonces moto d&rsquo;occasion en ligne !<br>
                   Augmentez la visibilité de votre annonce en ajoutant jusqu&rsquo;à 5 photos. <br>
             <strong><br>
               3. Réactivez votre annonce</strong> chaque mois jusqu&rsquo;à la vente gratuitement !
          
            
                 <strong><br>
                 <br>
                 Le PLUS Moto Expert : 1 site = 2 sites !</strong><br>
                   Vous déposez votre annonce sur <strong><a href="http://www.motoexpert.fr/">www.motoexpert.fr</a></strong> et votre moto sera également visible sur notre site partenaire <strong><a href="http://www.motofan.fr/">www.motofan.fr</a></strong> !
        
               
           
                   <br>
                   <br><center>
                     <a href="#"><img src="<?php echo MEDIA_URL ?>images/services/annonce.png" width="255" height="61"></a>
                   </center>
           </div>
           

          </div>
          <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a><p>&nbsp;</p> 
               	</div>
       	    </div>    
          
    </div>