<div id="content-978"> 
        
        
       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a></div>

            <div class="top-left"><span>OCCASION MOTO</span>
                         <p>&nbsp; </p>
                         
            </div>
        	</div>
           
           <?php
                 $config = Zend_Registry::get('config');
                 $ruta = $config->app->photoNews;
           ?>
            <div id="services-978"> <div class="services-978">
            <?= $this->ocasion[0]['value'];?><br>
<br>
<div class="services-imglir img100">
<img src="<?php echo MEDIA_URL ?>images/services/solutions.png" width="625" height="90">
</div><br><br>

<br>

<br>
<?= $this->ocasion[1]['value'];?>
</div>
          </div><div id="services-978">
           <div class="services-title-blue"><?= $this->ocasion[14]['value'];?></div>
           
           <div class="services-978"><div class="services-265">
           <img src="<?php echo $ruta.$this->ocasion[17]['value']?>" width="250" height="175"></div>
               <?php echo $this->ocasion[15]['value']?>
           <br>
        
             
               <br>
               <br>
              <?php echo $this->ocasion[16]['value']?>
           </div>
           
           </div>
          
         <div id="services-978">
           <div class="services-title-blue"> <?php echo $this->ocasion[5]['value']?></div>
           
           <div class="services-978"><div class="services-imglir">
                   <img src=" <?php echo $ruta.$this->ocasion[10]['value']?>" width="249" height="256"></div>
              <?php echo $this->ocasion[6]['value']?>
             <br>
             <br>
          
             
             <br>
             <br>
               <br>
             
              <?php echo $this->ocasion[7]['value']?>  
               <br>
               <div>
                 <div>
                    <?php echo $this->ocasion[8]['value']?><br>
                     <br><div class="services-imglir img100">
                         <img src="<?php echo $ruta.$this->ocasion[11]['value']?>" width="388" height="200"></div>
                      <?php echo $this->ocasion[9]['value']?>
                 </div>
               </div>
           </div>
          </div>

        <div id="services-978">
           <div class="services-title-blue"><?php echo $this->ocasion[20]['value']?></div>
           
           <div class="services-978"><div class="services-imglil"><img src="<?php echo $ruta.$this->ocasion[23]['value']?>" width="250" height="216"></div>
             
                <?php echo $this->ocasion[21]['value']?>
                 <br>
                 <?php echo $this->ocasion[22]['value']?>
                 
                   <br><center>
                     <?php if ($this->authData){?>
			<a  href="/compte"><img src="<?php echo MEDIA_URL ?>images/services/annonce.png" width="255" height="61"></a>
			<?php } else {?>
			<a href="/login"><img src="<?php echo MEDIA_URL ?>images/services/annonce.png" width="255" height="61"></a>
			<?php } ?>  
                     
                   </center>
           </div>
           

          </div>
          <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a><p>&nbsp;</p> 
               	</div>
       	    </div>    
          
    </div>