<div id="content-978"> 
        
        
       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a></div>

            <div class="top-left"><span>SERVICE RAPIDE</span>
                         <p> Des services d’Experts !</p>
                         
            </div>
        	</div>
           
           
            <div id="services-978">            
              <div class="services-video">
              		<iframe  src="//www.youtube.com/embed/SPbN2n-iAeM" frameborder="0" id="vodep" allowfullscreen></iframe>
              </div>
              <div class="services-video-link">
              	<a href="http://www.youtube.com/embed/SPbN2n-iAeM" target="vodep" class="btn-video">PRÉSENTATION</a>
                <a href="http://www.youtube.com/embed/ZYGXaw4PAH0" target="vodep" class="btn-video">RÉVISION ET FORFAITS</a>
                <a href="http://www.youtube.com/embed/CkhgWvF6YQY" target="vodep" class="btn-video">DIAGNOSTIC</a>
              </div>
              
              
          </div>
           <div id="services-978">
           <div class="services-title-blue">SERVICE RAPIDE, SERVICE LIMPIDE</div>
           
           <div class="services-978"><div class="services-265"><img src="<?php echo MEDIA_URL ?>images/service-d1.jpg" width="265" height="225"></div><p>QUALITÉ</p><br>
             Vous donner satisfaction, tel est notre objectif.<br>
             Nos mécaniciens sont des techniciens compétents, formés continuellement aux nouvelles technologies, aguerris à un diagnostic exact. Ils sont équipés de tous les outils spécifiques et nécessaires à des prestations de qualité.<br>
             <br>
             <p>PRIX</p><br>
             Un service rapide de qualité est un service sans mauvaise surprise, au juste prix. Nos tarifs sont affichés partout en France, dans nos magasins.<br>
             <br>
             <p>DÉLAI</p><br>
             Notre organisation et nos compétences nous permettent dmaîtriser précisément nos temps d’interventions. C’est pourquoi, nous nous engageons sur un délai annoncé.<br>
             Avec ou sans rendez-vous, un délai annoncé est un délai tenu.</div>
           
           </div>
          
         <div id="services-978">
           <div class="services-title-blue">ENTRETENEZ, RÉPAREZ, PERSONNALISEZ VOTRE MOTO DANS NOS ATELIERS !</div>
           
           <div class="services-978"><div class="services-235"><img src="<?php echo MEDIA_URL ?>images/service-d2.jpg" width="235" height="235"></div>
             <strong>Dans nos ateliers Moto Expert nous nous engageons à vous faciliter l’entretien de votre moto :</strong>
             <br>
             <br>
             <span><strong>L’accueil </strong></span>de votre moto en atelier avec ou sans rendez-vous 6 jours sur 7. <br>
               <br>
                <span><strong>La prise en charge</strong></span>de votre moto quelle que soit sa marque par des techniciens formés avec un outillage adapté. Nous disposons de toutes les pièces nécessaires à nos interventions, en stock ou sur commande. Nous nous fournissons chez les plus grands équipementiers pour vous proposer des pièces d’origine ou d’une qualité équivalente à l’origine. <br>
               <br>
               <span><strong>Transparent</strong> et <strong>sans surprise</strong>,</span> nos tarifs sont clairement affichés dans votre magasin et sur le site. Nous respectons nos devis.
               <br>
               <br>
               <span>Nous garantissons un <strong>service professionnel </strong></span>par la qualité de la formation de nos techniciens, de nos méthodes de travail et de nos équipements à la pointe de la technologie.<br>
           Nos ateliers vous proposent plus de 75 prestations pour l’entretien de votre moto.           </div>
           

          </div>
          
          
          <div id="services-978">
           <div class="services-title-blue">UN GESTE POUR L’ENVIRONNEMENT</div>
           
           <div class="services-978"><div class="services-234"><img src="<?php echo MEDIA_URL ?>images/service-d3.jpg" width="235" height="319"></div>
             <strong>MOTO EXPERT S’ENGAGE À RESPECTER L’ENVIRONNEMENT DANS CHACUN DE SES MAGASINS.</strong><br>
               Aujourd’hui, une vraie politique environnementale est en place, conforme aux directives européennes.<br>
               Le traitement des déchets dans nos magasins est une action quotidienne entreprise par tous nos collaborateurs pour préserver notre environnement.<br>
               <br>
             
             <strong>QUELS SONT LES DÉCHETS RETRAITÉS ?</strong><br>
               Aujourd’hui 90% des déchets dangereux et non dangereux générés par notre activité sont collectés et acheminés vers des filières de recyclage spécifiques.<br>
               <br>
               <strong>Les pneus</strong> sont retraités dans des infrastructures locales. Ils sont ensuite <br>
               redirigés vers des filières de valorisation énergétique, de valorisation matière (sous forme de “poudrettes”).<br>
               <br>
             <strong>Les huiles, emballages souillés, filtres</strong> sont collectés, puis recyclés ou valorisés dans des filières spécifiques de traitements de déchets industriels dangereux (DID). La gestion de ces déchets est suivie par l’émission d’un bordereau de suivi de déchets industriels. <br>
             <br>
             <strong>Le liquide de refroidissement</strong> est acheminé vers une filière de traitement chimique permettant d’éviter l’incinération coûteuse d’un point de vue écologique et économique. <br>
             <br>
             <strong>Les batteries</strong> sont collectées dans des bacs de stockage spécifiques et acheminés vers une filière de recyclage <br>
             dédiée, permettant le tri des matières, avec neutralisation de l’acide et valorisation du plastique, mais surtout recyclage du plomb.<br>
             <br>
            <strong>Les aérosols</strong> font l’objet d’un tri et d’un acheminement vers des filières de retraitement particulières. </div>
           

          </div>
          
          <div id="services-978">
           <div class="services-title-blue">CONDITIONS GÉNÉRALES DU SERVICE RAPIDE MOTO EXPERT</div>
           
           <div class="services-978">
             Les prix mentionnés sur le présent site sont des prix maximum conseillés.<br>
               <br>
               Les magasins MOTO EXPERT, en tant que magasins gérés par des sociétés indépendantes, fixent leur prix de vente librement. Ces prix peuvent donc varier selon la politique commerciale de chaque magasin. <br>
               <br>
             A ce titre nous vous invitons à prendre directement contact avec le magasin MOTO-EXPERT le plus proche de chez vous afin de vous assurer non seulement du prix pratiqué mais également de la disponibilité du produit ou du service concerné.
           </div>
           

          </div>
          

       	  <div id="content-top">
           	<div id="content-top"><a href="/franchise" class="service-prev">RETOUR</a><p>&nbsp;</p> 
               	</div>
       	    </div>    
          
    </div>