		
			<div class="row-fluid">
				<div class="span12 center login-header">
					<h2>Bienvenido "SYSADMIN"</h2>
				</div><!--/span-->
			</div><!--/row-->
			
			<div class="row-fluid">
				<div class="well span5 center login-box">
					<div class="alert alert-info">
						Por Favor Ingrese Su Usuario y Clave de Acceso
					</div>
					<form class="form-horizontal" method="post">
						<fieldset>
							<div class="input-prepend" data-rel="tooltip" data-original-title="Usuario ">
								<span class="add-on"><i class="icon-user"></i></span><input autofocus="" class="input-large span10" name="email" id="email" type="text" value="">
							</div>
							<div class="clearfix"></div>

							<div class="input-prepend" data-rel="tooltip" data-original-title="Clave Acceso">
								<span class="add-on"><i class="icon-lock"></i></span><input class="input-large span10" name="clave" id="clave" type="password" value="">
							</div>
							<div class="clearfix"></div>

							<!--<div class="input-prepend">
							<label class="remember" for="remember"><div class="checker" id="uniform-remember"><span><input type="checkbox" id="remember" style="opacity: 0;"></span></div>Remember me</label>
							</div>
							<div class="clearfix"></div>-->

							<p class="center span5">
							<button type="submit" class="btn btn-primary">Login</button>
							</p>
						</fieldset>
					</form>
				</div><!--/span-->
			</div><!--/row-->
				