<div id="pad-wrapper">                
                <div class="table-wrapper products-table section">
                    <div class="row-fluid head">
                        <div class="span10">
                            <h4>Contenido : </h4>
                        </div>
                        <div class="span2">
                        <a class="btn-flat success new-product" href="/admin/contenido/cargar">+ Cargar Contenido</a>
                        </div>
                        
                    </div>
                    

                    <div class="row-fluid filter-block">
                        <div class="pull-right">
                         <form method="get" action="/admin/contenido">
                            <div class="ui-select">
                                <?php echo $this->form->flag?>
                            </div>
                            <?php echo $this->form->busqueda?>
                        </form>  
                        </div>
                    </div>

                    <div class="row-fluid">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="span2">
                                        ID
                                    </th>
                                    <th class="span2">
                                        Artista
                                    </th>
                                    <th class="span3">
                                        Canción
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Genero
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Empresa
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Fecha Registro
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Fecha Validez
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Acciones
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- row -->
                                <?php foreach ($this->rbt as $item): ?>
                                <tr>
                                    <td>                                        
                                        <a href="/admin/contenido/editar/cod/<?=$item['idrbt'] ?>"><?=$item['idrbt'] ?></a>
                                    </td>
                                    <td>
                                        <?=$item['artista'] ?>
                                    </td>
                                    <td>
                                        <?=$item['cancion'] ?>
                                    </td>
                                    <td>
                                        <?=$item['genero'] ?>
                                    </td>
                                    <td>
                                        <?=$item['empresa'] ?>
                                    </td>
                                    <td>
                                        <?=$item['fecha_registro'] ?>
                                    </td>
                                    <td>
                                        <?=$item['fecha_valido'] ?>
                                    </td>
                                    <td>
                                        <a href="/admin/contenido/editar/cod/<?=$item['idrbt'] ?>">Modificar</a>
                                    </td>
                                    
                                </tr>
                                <?php endforeach; ?>                                
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- end products table -->

                
            </div>