<div id="content" class="paddin30">
	<div id="content-top">

		<div class="top-left">
			MOTO EXPERT <br />
			<span>MOTOS D'OCCASION</span>
		</div>
		<div class="top-right">VOUS VENDEZ VOTRE MOTO? NOUS NOUS OCCUPONS DE
			TOUT</div>
	</div>
	<div class="contentrechercher">
		<div class="contentrechercher-left">
			<h2>RECHERCHER UNE MOTO PARMI 1311 VÉHICULES</h2>
			<p>Rechercher une moto parmi 1311 véhicules d'occasion Vous souhaitez
				acheter une moto d'occasion. vous trouverez ici des centaines
				d'annonces récentes, détaillées et mises à jour quotidiennement.</p>
		</div>

		<div class="contentrechercher-right">

			<form id="form1" name="form1" method="post" action="">
				<div class="zone">
					<h2>ZONE GEOGRAPHIQUE</h2>
					<p>
						<label for="select3"></label> 
						<?= $this->form->deparment?> <label for="select2" class="selectlabel1"></label> 
						<?= $this->form->magasin?> <br /> <br /> <br /> <br />
					</p>
					<br />


				</div>
				<div class="vehicule">
					<h2>VEHICULE</h2>
					<label for="select4" class="selectlabel4"></label> 
					<?= $this->form->category?>
					<label for="select5" class="selectlabel1"></label> 
					<?= $this->form->marque?>
					 <label for="select5" class="selectlabel2"></label> 
					 
					 <?= $this->form->modele?>


				</div>
				<input type="submit" name="button2" id="button2" value="RECHERCHER " />
			</form>
			<!-- //magasins // -->
		</div>
	</div>
	<div id="poster">
		<div class="poster-left">VOUS VENDEZ VOTRE MOTO ? NOUS NOUS OCCUPONS
			DE TOUT</div>
		<div class="poster-right">POSTER VOTRE ANNONCE</div>
	</div>
	<div id="navigation">
		<div class="resultats">1349 RÉSUTATS TROUVÉS</div>
		<div class="next-prev">
			<a href="#" class="nprev">PRECEDENTE</a><a href="" class="nnext">SUIVANTE</a>
		</div>
		<div class="trier">
			<form id="form2" name="form2" method="post" action="">
				<label for="select6"></label> <select name="select6" id="select6">
					<option value="0">TRIER</option>
					<option value="0">TRIER 1</option>
					<option value="0">TRIER 2</option>
					<option value="0">TRIER 3</option>
				</select>
			</form>
		</div>
	</div>
	<!-- //***   //-->
	<div id="results-content">
		<div id="list_">
			<div class="result-col3">
				<h3>
					MOTO EXPERT <span>METZ</span>
				</h3>
				<div class="result-imgs">
					<img src="images/resutats-img.jpg" width="300" height="115" />
				</div>
				<div class="result-price">4200 €</div>
				<div class="result-desc">
					<div class="result-date">05/02114</div>
					<p>
						<strong>Suzuki RMZ 250</strong><br /> Honda - CB 600 F ABS - 600
						cm3 - 15550 km Année 2005 - à débattre
					</p>
					<a href="#" class="visuel">CONTRÛLE VISUEL</a> <a href="#"
						class="garantie">GARANTIE </a>
				</div>

			</div>
		</div>
		<div class="result-col3">
			<h3>
				MOTO EXPERT 2<span>METZ</span>
			</h3>
			<div class="result-imgs">
				<img src="images/resutats-img.jpg" width="300" height="115" />
			</div>
			<div class="result-price">4200 €</div>
			<div class="result-desc">
				<div class="result-date">05/02114</div>
				<p>
					<strong>Suzuki RMZ 250</strong><br /> Honda - CB 600 F ABS - 600
					cm3 - 15550 km Année 2005 - à débattre
				</p>
				<a href="#" class="visuel">CONTRÛLE VISUEL</a> <a href="#"
					class="garantie">GARANTIE </a>
			</div>

		</div>
		<div class="result-col3 col3no">
			<h3>
				MOTO EXPERT 3<span>METZ</span>
			</h3>
			<div class="result-imgs">
				<img src="images/resutats-img.jpg" width="300" height="115" />
			</div>
			<div class="result-price">4200 €</div>
			<div class="result-desc">
				<div class="result-date">05/02114</div>
				<p>
					<strong>Suzuki RMZ 250</strong><br /> Honda - CB 600 F ABS - 600
					cm3 - 15550 km Année 2005 - à débattre
				</p>
				<a href="#" class="visuel">CONTRÛLE VISUEL</a> <a href="#"
					class="garantie">GARANTIE </a>
			</div>

		</div>


</div>


	<div id="navigation">
		<div class="resultats">1349 RÉSUTATS TROUVÉS</div>
		<div class="next-prev">
			<a href="#" class="nprev">PRECEDENTE</a><a href="" class="nnext">SUIVANTE</a>
		</div>
		<div class="trier">
			<form id="form2" name="form2" method="post" action="">
				<label for="select6"></label> <select name="select6" id="select6">
					<option value="0">TRIER</option>
					<option value="0">TRIER 1</option>
					<option value="0">TRIER 2</option>
					<option value="0">TRIER 3</option>
				</select>
			</form>
		</div>
	</div>
</div>

<script src="<?php echo MEDIA_URL ?>js/marque-back.js"></script>

<script>
$(function(){
    
    var combodep = {        
        init : function() {
           this.Combo("#marque", "#modele", "--- MARQUE ---", "/default/index/get-modele", "id", "value");           
        },        
        Combo : function (c, cd, def, url, fieldv, fields) {            
            
                var actual = $(c);
                
                if (actual.val() != 0) {                    
                    
                    $(cd).removeAttr("disabled");
                    $.ajax({
                        url: url,
                        type: 'post',
                        data: {
                           id : actual.val()
                        },
                        dataType: 'json',                        
                        success: function(data){
                                $(cd).html("<option value='0'> -- Modele -- </option>");


                                $.each(data, function(index, value){
                                	var select = ' ';
                                	if (value[fieldv] == '<?php echo $this->announce['modele']?>')
                                         var selec = 'selected="selected "';
                                    
                                    $(cd).append("<option "+ selec +" value='"+value[fieldv]+"'>"+value[fields]+"</option>");
                                });

                                
                        }
                    });                    
                } else {
                    $(cd).html("");
                    $(cd).append("<option value='0'> -- Modele -- </option>");
                    $(cd).attr("disabled", "disabled");
                    
                    
                }
            
       }
    };    
    combodep.init();
    
});



</script>