<div id="content" class="paddin30">
	<div id="content-top">

		<div class="top-left">
			MOTO EXPERT <br />
			<span>MOTOS D'OCCASION</span>
		</div>
		<div class="top-right">VOUS VENDEZ VOTRE MOTO ? NOUS NOUS OCCUPONS DE
			TOUT</div>
	</div>
	<div class="contentrechercher">
		<div class="contentrechercher-left">
			<h2>RECHERCHER UNE MOTO PARMI <?php echo $this->total; // if($this->total > $this->totalAnuncio['totalAnnounce']){echo $this->total; }else{ echo $this->totalAnuncio['totalAnnounce'];}?> VÉHICULES</h2>
			<p>Rechercher une moto parmi <?php echo $this->total; //if($this->total > $this->totalAnuncio['totalAnnounce']){echo $this->total; }else{ echo $this->totalAnuncio['totalAnnounce'];}?> véhicules d'occasion. Vous souhaitez
				acheter une moto d'occasion. vous trouverez ici des centaines
				d'annonces récentes, détaillées et mises à jour quotidiennement.</p>
		</div>

		<div class="contentrechercher-right">
                        <script>
    
                        $(function() {
                            $('#tienda').change(function() {
                               
                                    $('#tienda').submit();
                            });
                        });
                        $(function() {
                            $('#magasin').change(function() {
                                    $('#magasin').submit();
                            });
                        });
                        </script>
			<form id="form2" name="form2" method="get" action="">
				<div class="zone">
					<h2>ZONE GEOGRAPHIQUE</h2>
					<p>
						<label for="select3"></label> 
						<?= $this->form->deparment?> <label for="select2" class="selectlabel1"></label> 
						<?= $this->form->magasin?> <br /> <br /> <br /> <br />
					</p>
					<br />


				</div>
				<div class="vehicule">
					<h2>VEHICULE</h2>
					<label for="select4" class="selectlabel4"></label> 
					<?= $this->form->category?>
					<label for="select5" class="selectlabel1"></label> 
					<?= $this->form->marque?>
					 <label for="select5" class="selectlabel2"></label> 
					 <?= $this->form->modele?>
					 
					 <input type="hidden" name="trier" value="<?= (isset($_GET['trier']))?$_GET['trier']:''; ?>">
					 <input type="hidden" name="page" value="<?= (isset($_GET['page']))?$_GET['page']:''; ?>">
				</div>
				<input type="submit" name="button2" id="button2" value="RECHERCHER" />
			</form>
			<!-- //magasins // -->
		</div>
	</div>
	<div id="poster">
		<div class="poster-left">VOUS VENDEZ VOTRE MOTO ? NOUS NOUS OCCUPONS
			DE TOUT</div>
            <div class="poster-right">
                 <?php if ($this->authData){?>
                <a class="actualite-linkof" href="/compte/annonce-publier"><p>POSTER VOTRE ANNONCE</p></a>
                <?php } else {?>
                    <a class="actualite-linkof" href="/login"><p>POSTER VOTRE ANNONCE</p></a>
                <?php } ?>
            </div>
	</div>
	<div id="navigation">
		<div class="resultats"><?php echo $this->total ?> RÉSUTATS TROUVÉS</div>
		<div class="next-prev">
<?php 

$ruta = "";
$i=true;
foreach ($this->prueba as $index => $value):
if ($value != "0" and !is_null($value) and $index != "page" and $index != "trier") {
	if ($i) {
		$ruta.= $index."=".$value;
	}
	else
		$ruta.= "&".$index."=".$value;
	$i= false;
}


endforeach;
?>		
<?php $page = ''; if (isset($this->page) and $this->page > 1) $page="&page=".$this->page;?>		
			
<?php echo $this->paginationControl($this->result, 'Sliding', '_pag.phtml', array('prueba' => $this->prueba, 'ruta' => $ruta, 'trier' => $this->trier));?>		
			
			
		</div>		
		<div class="trier">
			<form id="form" name="form" method="post" action="">
				<label for="select6"></label>
				 
				<select name="trier" id="trier"  onchange="this.form.action = this.value; this.disabled = true; this.form.submit()" >
					<option value="0">TRIER</option>
					<option value="/annonces?<?= $ruta ?>&trier=date_asc<?= $page?>" <?php if ($this->trier == "date_asc") echo "selected ='selected'"  ?>>Date +</option>
					<option value="/annonces?<?= $ruta ?>&trier=date_desc<?= $page?>" <?php if ($this->trier == "date_desc") echo "selected ='selected'"  ?>>Date -</option>
					<option value="/annonces?<?= $ruta ?>&trier=prix_desc<?= $page?>" <?php if ($this->trier == "prix_desc") echo "selected ='selected'"  ?>>Prix +</option>
					<option value="/annonces?<?= $ruta ?>&trier=prix_asc<?= $page?>" <?php if ($this->trier == "prix_asc") echo "selected ='selected'"  ?>>Prix -</option>
				</select>
			</form>
		</div>
	</div>
	<!-- //***   //-->
	<div id="results-content">
	<!-- <div class="result-col3 col3no">-->
	<?php $i=0;if ($this->result)foreach ($this->result as $item):$i++;?>
		
			<div class="result-col3 <?php  if ($i % 3 == 0) echo "col3no";?>">
                                <?php
                                if($item['id_me']!=""){
                                ?>
				<h3>
				MOTO EXPERT<span><?= $item['ville']?></span>
				</h3>
                                <?php }else{?>
                                <h3>
                                    Particulier <span>dep. <?= $item['departement']?></span>
				</h3>
                                <?php }?>
				<div class="result-imgs">
                                    <?php
                                    $config = Zend_Registry::get('config');
                                    $foto = str_replace(",",".",$item['foto']);    
                                    $ruta = $config->app->photoUrl.$item['departement'].'/'.$foto;
                                    ?>
                                    <a href="Fiche-Moto/index/id/<?php echo $item['id'];?>">
                                        <img src="<?=$ruta;?>" width="300" />
                                    </a>
				</div>
				<div class="result-price"><?=($item['prix'] > 0) ? $item['prix'].' €' : 'A débattre'?></div>
				<div class="result-desc">
					<div class="result-date">
                                            
                                            <?php 
                                            $d = new App_Date_Calc();
                                            echo  $d->daysToDate($item['date'], "%d/%m/%y");
                                            
                                            ?>
                                        </div>
					<p>
						<strong><?=$item['titre']?></strong><br /> 
						<?php echo $item['marque']. " " . $item['modele'] . " " . $item['cylindree']. " cm3 " . $item['km']. " km" . " Année " . $item['annee']?>
					</p>
                                        <?php if ($item['controle']==1){?>
					<span  class="visuel">CONTRÛLE VISUEL</span>
                                        <?php }?>
                                        <?php if ($item['isgarantie']==1){?>
                                        <span class="garantie">GARANTIE </span>
                                        <?php }?>
				</div>

			</div>
		
	<?php endforeach; ?>
		

<!-- fin result -->
</div>


	<div id="navigation">
		<div class="resultats"><?php echo $this->total; ?> RÉSUTATS TROUVÉS</div>
		<div class="next-prev">
<?php echo $this->paginationControl($this->result, 'Sliding', '_pag.phtml', array('prueba' => $this->prueba, 'ruta' => $ruta, 'trier' => $this->trier));?>		
		</div>
		<!-- <div class="trier">
			<form id="form2" name="form2" method="post" action="">
				<label for="select6"></label> <select name="select6" id="select6">
					<option value="0">TRIER</option>
					<option value="0">TRIER 1</option>
					<option value="0">TRIER 2</option>
					<option value="0">TRIER 3</option>
				</select>
			</form>
		</div>-->
	</div>
</div>

<script src="<?php echo MEDIA_URL ?>js/marque-back.js"></script>

<script>
$(function(){
    
    var combodep = {        
        init : function() {
           this.Combo("#marque", "#modele", "--- MARQUE ---", "/default/index/get-modele", "id", "value");           
        },        
        Combo : function (c, cd, def, url, fieldv, fields) {            
            
                var actual = $(c);
                
                if (actual.val() != 0) {
                                        
                    
                    $(cd).removeAttr("disabled");
                    $.ajax({
                        url: url,
                        type: 'post',
                        data: {
                           id : actual.val()
                        },
                        dataType: 'json',                        
                        success: function(data){
                                $(cd).html("<option value='0'> -- Modele -- </option>");


                                $.each(data, function(index, value){
                                	var selec = ' ';
                                	if (value[fieldv] == "<?php echo @$this->announce['modele']?>")
                                         var selec = 'selected="selected "';
                                    
                                    $(cd).append("<option "+ selec +" value='"+value[fieldv]+"'>"+value[fields]+"</option>");
                                });

                                
                        }
                    });                    
                } else {
                    $(cd).html("");
                    $(cd).append("<option value='0'> -- Modele -- </option>");
                    $(cd).attr("disabled", "disabled");
                    
                    
                }
            
       }
    };    
    combodep.init();
    
});



</script>
