
<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="js/scroll.js"></script>
		<script type="text/javascript">
		$(document).ready(function()
		{
			$('#results-content').scrollExtend(
			{
				'target': '#list_',
				'url': 'scroll.php'
			});
		});
		</script>

		
        <div id="content" class="paddin30"> 
        	<div id="content-top">
            
                            <div class="top-left">MOTO EXPERT <br /><span>L’ACTU</span></div>
                            <div class="top-right"></div>
            </div>
        	<div class="contentrechercher not-top">
       		  <div class="contentrechercher-left">
               	<h2>RECHERCHER UNE ACTUALITÉ</h2>
              <p>Retrouvez en un coup d’oeil les dernières actualités postées sur le site de Moto Expert. Faites profiter vos amis des news de tout le réseau de moto expert !</p>
       		  </div>
                
              <div class="contentrechercher-right">
                
                <form id="form1" name="form1" method="post" action="">
                <div class="zone">
                   	  <h2>ACTUALITÉ RÉSEAU</h2>
                  <p>
                    <label for="select3"></label>
                    <select name="select3" id="select3">
                          <option value="0" selected="selected">Toute l’actu </option>
                          <option value="1">Département  1</option>
                          <option value="2">Département  2</option>
                          <option value="3">Département  3</option>
                          <option value="4">Département  4</option>
                          <option value="5">Département  5</option>
                          <option value="6">Département  6</option>
                    </select> 
                    <label for="select2" class="selectlabel1"></label>
                    <select name="select2" id="select2">
                          <option value="0" selected="selected">Magasin </option>
                          <option value="1">Magasin  1</option>
                          <option value="2">Magasin  2</option>
                          <option value="3">Magasin  3</option>
                          <option value="4">Magasin  4</option>
                          <option value="5">Magasin  5</option>
                          <option value="6">Magasin  6</option>
                    </select>
                    
                    <br />
                    <br />
                    <br />
                    <br />
                  </p>
                  <br />
                              
                        <input type="submit" name="button2" id="button2" value="RECHERCHER " />
                  </div>
                    </form>
                    <div class="vehicule">
                   	  <h2>L’ACTU MOTO EXPERT</h2>
                          <form id="form1" name="form1" method="post" action="">
                  <label for="select4" class="selectlabel4"></label>
                  <select name="select4" id="select4">
                                	<option value="0" selected="selected">Toute l’actu</option>
                                    <option value="1">Catégorie 1</option>
                                    <option value="2">Catégorie 2</option>
                                    <option value="3">Catégorie 3</option>
                                    <option value="4">Catégorie 4</option>
                                    <option value="5">Catégorie 5</option>
                                    <option value="6">Catégorie 6</option>
                      </select>
                      <label for="select5" class="selectlabel1"></label>
                      <label for="select5" class="selectlabel2"></label>
                    <input type="submit" name="button2" id="button2" class="rechercher" value="RECHERCHER " />
                </form></div>
              <!-- //magasins // --></div>
        	</div>
          
          <div id="navigation" class="not-navi">
          	<div class="resultats">30 RÉSUTATS TROUVÉS </div>
            <div class="next-prev">
            	<a href="#" class="nprev">PRECEDENTE</a><a href="#" class="nnext">SUIVANTE</a>
            </div>
          </div>
          <!-- //***   //-->
          <div id="not-content">
          	<div class="content-not">
             	<div class="not-list">
                	<div class="not-title">MOTO EXPERT <span>METZ</span></div>
                    <div class="not-body">
                    	<div class="not-body-img"><img src="images/not1.jpg" width="200" /></div><div class="not-subtitle">Atelier: réparations, entretiens et révisions pour toutes les marques de moto</div>Le magasin MOTO EXPERT ALENCON vous propose ses services atelier:
vidanges, freins, joints spys de fourches, embrayages, révisions, synchro carburateur, jeu aux soupapes, remplacement des courroies de distribution sur les DUCATI, réparation des accidentées ainsi que les grosses réparations moteurs, boîtes...<div class="not-btn"><a href="#" class="btn-not">LIRE LA SUITE</a></div></div>
                </div>
                             	<div class="not-list">
                	<div class="not-title">MOTO EXPERT <span>METZ</span></div>
                    <div class="not-body">
                    	<div class="not-body-img"><img src="images/not2.jpg" width="200" /></div><div class="not-subtitle">Atelier: réparations, entretiens et révisions pour toutes les marques de moto</div>Le magasin MOTO EXPERT ALENCON vous propose ses services atelier:
vidanges, freins, joints spys de fourches, embrayages, révisions, synchro carburateur, jeu aux soupapes, remplacement des courroies de distribution sur les DUCATI, réparation des accidentées ainsi que les grosses réparations moteurs, boîtes...<div class="not-btn"><a href="#" class="btn-not">LIRE LA SUITE</a></div></div>
                </div>
                             	<div class="not-list">
                	<div class="not-title">MOTO EXPERT <span>METZ</span></div>
                    <div class="not-body"><div class="not-subtitle">Atelier: réparations, entretiens et révisions pour toutes les marques de moto</div>
                      Le magasin MOTO EXPERT ALENCON vous propose ses services atelier:
vidanges, freins, joints spys de fourches, embrayages, révisions, synchro carburateur, jeu aux soupapes, remplacement des courroies de distribution sur les DUCATI, réparation des accidentées ainsi que les grosses réparations moteurs, boîtes...<div class="not-btn"><a href="#" class="btn-not">LIRE LA SUITE</a></div></div>
                </div>
                             	<div class="not-list">
                	<div class="not-title">MOTO EXPERT <span>METZ</span></div>
                    <div class="not-body">
                    	<div class="not-body-img"><img src="images/not1.jpg" width="200" /></div><div class="not-subtitle">Atelier: réparations, entretiens et révisions pour toutes les marques de moto</div>Le magasin MOTO EXPERT ALENCON vous propose ses services atelier:
vidanges, freins, joints spys de fourches, embrayages, révisions, synchro carburateur, jeu aux soupapes, remplacement des courroies de distribution sur les DUCATI, réparation des accidentées ainsi que les grosses réparations moteurs, boîtes...<div class="not-btn"><a href="#" class="btn-not">LIRE LA SUITE</a></div></div>
                </div>
                             	<div class="not-list">
                	<div class="not-title">MOTO EXPERT <span>METZ</span></div>
                    <div class="not-body">
                    	<div class="not-body-img"><img src="images/not2.jpg" width="200" /></div><div class="not-subtitle">Atelier: réparations, entretiens et révisions pour toutes les marques de moto</div>Le magasin MOTO EXPERT ALENCON vous propose ses services atelier:
vidanges, freins, joints spys de fourches, embrayages, révisions, synchro carburateur, jeu aux soupapes, remplacement des courroies de distribution sur les DUCATI, réparation des accidentées ainsi que les grosses réparations moteurs, boîtes...<div class="not-btn"><a href="#" class="btn-not">LIRE LA SUITE</a></div></div>
                </div>
           	  <div class="not-list">
                	<div class="not-title">MOTO EXPERT <span>METZ</span></div>
                    <div class="not-body"><div class="not-subtitle">Atelier: réparations, entretiens et révisions pour toutes les marques de moto</div>
                      Le magasin MOTO EXPERT ALENCON vous propose ses services atelier:
vidanges, freins, joints spys de fourches, embrayages, révisions, synchro carburateur, jeu aux soupapes, remplacement des courroies de distribution sur les DUCATI, réparation des accidentées ainsi que les grosses réparations moteurs, boîtes...<div class="not-btn"><a href="#" class="btn-not">LIRE LA SUITE</a></div></div>
              </div>
            
                       	  <div class="not-list">
                	<div class="not-title">MOTO EXPERT <span>METZ</span></div>
                    <div class="not-body"><div class="not-subtitle">Atelier: réparations, entretiens et révisions pour toutes les marques de moto</div>
                      Le magasin MOTO EXPERT ALENCON vous propose ses services atelier:
vidanges, freins, joints spys de fourches, embrayages, révisions, synchro carburateur, jeu aux soupapes, remplacement des courroies de distribution sur les DUCATI, réparation des accidentées ainsi que les grosses réparations moteurs, boîtes...<div class="not-btn"><a href="#" class="btn-not">LIRE LA SUITE</a></div></div>
              </div>
            </div>
          
          </div>
            
            
            
            
            
            
            
            
            
                      <div id="navigation">
          	<div class="resultats">30 RÉSUTATS TROUVÉS </div>
            <div class="next-prev">
            	<a href="#" class="nprev">PRECEDENTE</a><a href="" class="nnext">SUIVANTE</a>
            </div>
          </div>
          </div>
          
          
          
          
          

          
          
          
     