<div id="det-content">
	<div id="content-top">

		<div class="top-left">
			MOTO EXPERT<br /> <span>L’ACTU</span>
		</div>
	</div>
	<div id="navi-fiche" class="det-nav">
		<a href="/news" class="previus">RETOUR A LA LISTE DES ACTUS </a>


		<div class="align-right text-right">
			<?php echo $this->paginationControl($this->result, 'Sliding', '_pagdetailnews.phtml', array('prueba' => $this->prueba)); ?>
		</div>

	</div>
	<!-- //*** DETAILS  //-->
	<?php 
        $config = Zend_Registry::get('config');
        $host = $config->app->photoNews;
        
        
        $url = $_SERVER['HTTP_HOST'].$_SERVER["REQUEST_URI"];
        
        foreach ($this->result as $item):?>
	<div id="details-not">
		<div class="col2 align-left">
                    <?php
                     
                                    $ruta = $config->app->photoNews.$item['image_1'];
                                    if($item['image_1'] !=""):
                    ?>
			
                        <img src="<?= $ruta; ?>">
                    <?php  endif;?>
		</div>


		<div class="col2 align-right det-not">
			<div class="partager det-part">
			
                            <a href="javascript: void(0);" 
                                   onclick="window.open('http://www.facebook.com/sharer.php?u=<?php echo $url;?>',
                                                                                'ventanacompartir', 
                                                                                'toolbar=0, status=0, width=650, height=450');"><img
					src="<?=MEDIA_URL ?>images/p-facebook.jpg" width="26" height="26" /></a>
                            
                            
                            <a href="http://twitter.com/home?status=Leyendo  . <?php echo "Noticias"?>.  en  http://www.motoexpert.fr/ " class="btwitter" title="Compartelo en Twitter" target="_blank">
                                <img src="<?=MEDIA_URL ?>images/p-twitter.jpg" width="26" height="26" />
                            </a> 
                            
                            
                            
                                Partager
				<div class="det-subtitle">
                                        <?php
                                        $idTienda = explode('_', $item['id_parent']);
                                        $modelMaga = new App_Model_Magasin();
                                        $resultMaga = $modelMaga->getMagasin($idTienda[1]);
                                       
                                        ?>
					MOTO EXPERT <span><?= $resultMaga['ville']?></span>
					
				</div>
			</div>
			
			<h2><?= $item["titre"]?></h2>

			<div class="col2  align-left">
				<p>
                                    Le magasin MOTO EXPERT <?= $resultMaga['ville'];?> vous propose ses services atelier:<br>
				<br>
				</p>
				<p>
					<?= $item["texte_1"]?>
					<br> <br>
				</p>
				<p>
				<?= $item["titre_1"]?>
				</p>
				<p></p>

			</div>
		</div>
		<div style="width: 100%; height: 10px; clear: both"></div>
		<div class="col2 align-left">
			<div class="det-subtitle-red">Révisions toutes marques</div>
			<br> Le magasin MOTO EXPERT  <?= $resultMaga['ville'];?> vous propose ses services
			atelier:
			</p>
			<br>
			<p>
				<?= $item["texte_2"]?><br> <br>
			</p>
			<p><?= $item["titre_2"]?></p>

		</div>

		<div class="col2  align-right">
                    <?php
                     $config = Zend_Registry::get('config');
                                    $ruta = $config->app->photoNews.$item['image_2'];
                                    if($item['image_2'] !=""):
                    ?>
			<br> <br> 
                                <img src="<?= $ruta; ?>">
                    <?php  endif;?>
		</div>

		<div style="width: 100%; height: 10px; clear: both"></div>
                <?php
                if($item["video_1"]!=""):
                ?>
		<div class="det-video">
			<a href="#" class="det-download">Télécharger la documentation</a>
			<div class="det-subtitle-red">Découvrez le produit en vidéo</div>
			<div>
				<iframe src="//<?= $item["video_1"]?>" frameborder="0"
					id="vodep" allowfullscreen>
				</iframe>
				<br> Le magasin MOTO EXPERT ALENCON vous propose ses services
				atelier.
			</div>
			<a href="#" class="det-visitez">Visitez le site</a>

			<div class="det-subtitle-red">Découvrez le produit en image</div>


		</div>
                <?php endif;?>
		<!--<div class="det-cont-img">
			<div class="det-img">
				<a href="#">
				<img src="<?=MEDIA_URL ?>images/p1.jpg">
				<? //= $item["image_1"]?> 
				</a>
			</div>
			<div class="det-img">
				<a href="#"><img src="<?=MEDIA_URL ?>images/p2.jpg"> </a>
			</div>
			<div class="det-img">
				<a href="#"><img src="<?=MEDIA_URL ?>images/p1.jpg"> </a>
			</div>
			<div class="det-img">
				<a href="#"><img src="<?=MEDIA_URL ?>images/p2.jpg"> </a>
			</div>
			<div class="det-img">
				<a href="#"><img src="<?=MEDIA_URL ?>images/p1.jpg"> </a>
			</div>
			<div class="det-img">
				<a href="#"><img src="<?=MEDIA_URL ?>images/p2.jpg"> </a>
			</div>
			<div class="det-img">
				<a href="#"><img src="<?=MEDIA_URL ?>images/p1.jpg"> </a>
			</div>
			<div class="det-img nomargin">
				<a href="#"><img src="<?=MEDIA_URL ?>images/p2.jpg"> </a>
			</div>


		</div>-->
	</div>
	<?php endforeach;?>





	<div id="navi-fiche">
		<a href="#" class="previus">RETOUR A LA LISTE D'ANNONCES </a>


		<div class="align-right">
			<?php echo $this->paginationControl($this->result, 'Sliding', '_pagdetailnews.phtml', array('prueba' => $this->prueba)); ?>			
		</div>

	</div>
</div>
