
<div id="content-p28">
<div id="content-top">
            
                            <div class="top-left"><span>MON COMPTE</span></div>
        	</div>
            <div id="gerez">
            
           		 <div id="gerez-left">
                 <h2>GEREZ VOS INFORMATIONS<br /> PERSONNELLES</h2>
                 <div id="new-navigation"><span>VOS COORDONNÉES </span> </div>
                 <p class="in-radio"> Civilité : <?php echo $this->datos["civilite"]?></p>
                 <p class="in-radio"><?php echo $this->datos["nom"]?></p>
                 <p class="in-radio"><?php echo $this->datos["prenom"]?></p>
                 <p class="in-radio"><?php echo $this->datos["adresse"]?></p>
                 <p class="in-radio"><?php echo $this->datos["code_postal"]?></p>
                 <p class="in-radio"><?php echo $this->datos["ville"]?></p>
                <p class="in-radio"><?php echo $this->datos["pays"]?></p>
                 <p class="in-radio"><?php echo $this->datos["tel"]?></p>
                 <p class="in-radio"><?php echo $this->datos["portable"]?></p>
              <p class="in-radio"> </p>
                 <div id="new-navigation"><span>VOS INFORMATIONS DE CONNECTION</span> </div>
                                  
                 <p class="in-radio">Votre adresse Email :</p>
                 <p class="in-radio"><?php echo $this->datos["email"]?></p>
                 <p><a href="/compte/modifier-client" class="btn-100" >MODIFIER</a></p>

                 
                 </div>
            	 <div id="gerez-right">
                    <h2>GEREZ VOS ANNONCES</h2>
                    <p class="p14">Vous trouverez ci-dessous la liste de vos annonces déposées sur le site Moto Expert.</p>
                    
                    <?php foreach ($this->result as $item): 
                        
                    $foto = str_replace(",",".",$item['nom_fichier']);
                    ?>
                    <div class="gerez-block">
                        <div class="gerez-block1" >
                        <img src="<?php echo $this->ruta.$item['departement']."/".$foto; ?>" width="64" height="64">
                        </div>
                        <div class="gerez-block2" >
                        <span>Ref. : <?= $item['ref']?></span><br>
                          <span> <?php  
                          $d = new App_Date_Calc();
                            echo  $d->daysToDate($item['date'], "%d/%m/%y");
                         
                           ?> </span><br>
                          <?= $item['titre']?><br>
                          <?= $item['prix']?> € <br>
                        </div>
                        <div class="gerez-block3" ><?php echo ($item['ispayed']== "0")?'Désactivée':'Activée';?><br>
                        sur le site</div>
                        <?php if ($item['ispayed']== "0") {?>
                    	<div class="gerez-block4" ><a href="#" class="btn-gerez" >REACTIVER</a></div>
                    	<?php } ?>
                    	<div class="gerez-block5" ><a href="/compte/annonce-publier/modifier/annonce/<?= $item['id']?>" class="btn-gerez" >MODIFIER</a></div>
                    	<div class="gerez-block6" ><a href="#" class="btn-gerez" >SUPPRIMER</a></div>
                    </div>
                    <?php endforeach;?>
                    
                    <a href="/compte/annonce-publier" class="btn-100" >DEPOSER UNE ANNONCE</a>
                    <div class="gerez-text">Pour modifier les informations relatives à une annonce cliquez sur “Modifier”. 
                      <br>
                      L’annonce reste modifiable à tout moment.
                      <br>
                      Pour visualiser une annonce cliquez sur “Modifier”.
                      <br>
                   Pour supprimer une annonce cliquez sur “Supprimer”.</div>
<div class="gerez-desc">
La publication sur motoexpert.fr de petites annonces moto d’occasion est exclusivement réservée pour les ventes de particulier à particulier et pour les membres du réseau Moto Expert. Moto Expert se réserve le droit de supprimer toutes annonces qui ne correspondraient pas.
Après la création de votre annonce, celle-ci paraîtra sur le site après validation sous 48h ouvrable.
Toute modification d’une annonce engendre sa revalidation.</div>
                    
                    
              </div>
       	  
          <!-- //*** DETAILS  //-->

          
          
          
          <br />
          </div>
</div>