
<div id="content-p28">
<div id="content-top">
            
                            <div class="top-left"><span>MON COMPTE</span></div>
        	</div>
            <div id="gerez">
            
           		 <div id="gerez-left">
                 <h2>GEREZ VOS INFORMATIONS<br /> PERSONNELLES</h2>
                 <div id="new-navigation"><span>VOS COORDONNÉES </span> </div>
                 <p class="in-radio"> Civilité : <?php echo $this->authData->civilite?></p>
                 <p class="in-radio"><?php echo $this->authData->nom?></p>
                 <p class="in-radio"><?php echo $this->authData->prenom?></p>
                 <p class="in-radio"><?php echo $this->authData->adresse?></p>
                 <p class="in-radio"><?php echo $this->authData->code_postal?></p>
                 <p class="in-radio"><?php echo $this->authData->ville?></p>
                <p class="in-radio"><?php echo $this->authData->pays?></p>
                 <p class="in-radio"><?php echo $this->authData->tel?></p>
                 <p class="in-radio"><?php echo $this->authData->portable?></p>
              <p class="in-radio"> </p>
                 <div id="new-navigation"><span>VOS INFORMATIONS DE CONNECTION</span> </div>
                                  
                 <p class="in-radio">Votre adresse Email :</p>
                 <p class="in-radio"><?php echo $this->authData->email?></p>
                 <p><a href="/compte/modifier" class="btn-100" >MODIFIER</a></p>

                 
                 </div>
            	 <div id="gerez-right">
                    <h2>GEREZ VOS ANNONCES</h2>
                    <p class="p14">Vous trouverez ci-dessous la liste de vos annonces déposées sur le site Moto Expert.</p>
                    
                    <?php foreach ($this->result as $item):?>
                    <div class="gerez-block">
                        <div class="gerez-block1" ><img src="images/img.jpg" width="64" height="64"></div>
                        <div class="gerez-block2" >
                        <span>Ref. : <?= $item['ref']?></span><br>
                          <span> <?php  if ($item['date_valid']) echo date('d-m-y', $item['date_valid'])?> </span><br>
                          <?= $item['titre']?><br>
                          <?= $item['prix']?> € <br>
                        </div>
                        <div class="gerez-block3" ><?php echo ($item['stat']== "0")?'Activée':'Désactivée';?><br>
                        sur le site</div>
                        <?php if ($item['stat']== "0") {?>
                    	<div class="gerez-block4" ><a href="#" class="btn-gerez" >REACTIVER</a></div>
                    	<?php } ?>
                    	<div class="gerez-block5" ><a href="#" class="btn-gerez" >MODIFIER</a></div>
                    	<div class="gerez-block6" ><a href="#" class="btn-gerez" >SUPPRIMER</a></div>
                    </div>
                    <?php endforeach;?>
                    
                    <a href="#" class="btn-100" >DEPOSER UNE ANNONCE</a>
                    <div class="gerez-text">Pour modifier les informations relatives à une annonce cliquez sur “Modifier”. 
                      <br>
                      L’annonce reste modifiable à tout moment.
                      <br>
                      Pour visualiser une annonce cliquez sur “Modifier”.
                      <br>
                   Pour supprimer une annonce cliquez sur “Supprimer”.</div>
<div class="gerez-desc">
La publication sur motoexpert.fr de petites annonces moto d’occasion est exclusivement réservée pour les ventes de particulier à particulier et pour les membres du réseau Moto Expert. Moto Expert se réserve le droit de supprimer toutes annonces qui ne correspondraient pas.
Après la création de votre annonce, celle-ci paraîtra sur le site après validation sous 48h ouvrable.
Toute modification d’une annonce engendre sa revalidation.</div>
                    
                    
              </div>
       	  
          <!-- //*** DETAILS  //-->

          
          
          
          <br />
          </div>
</div>