<?php

if (!empty($this->ruta)) $sim ="&"; else $sim ="";
?>

<?php if (isset($this->previous)):?>
<a href="<?php echo "/annonces?".$this->ruta. $sim. "page=".$this->previous;?><?php if ($this->trier) echo "&trier=".$this->trier ?>" 
	class="nprev" data="<?php echo $this->previous;?>">PRECEDENTE</a>

<?php else: ?>
<!-- <a href="#" class="nprev disabled">PRECEDENTE</a>-->
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)):
?>
<?php if (!empty($this->ruta)) $sim ="&"; else $sim ="";?>
<a href="<?php echo "/annonces?".$this->ruta. $sim."page=".$this->next;?><?php if ($this->trier) echo "&trier=".$this->trier ?>"
	class="nnext" data="<?php echo $this->next;?>">SUIVANTE</a>
<?php else: ?>
<!-- <a href="#" class="nnext disabled">SUIVANTE</a>-->
<?php endif; ?>


