<?php
$ruta = "";
$i=true; 
foreach ($this->prueba as $index => $value):
if ($value != "0" and !is_null($value) and $index != "page") {	
	if ($i) {
		$ruta.= $index."=".$value;		
	}  
	else 
		$ruta.= "&".$index."=".$value;
$i= false;	
} 

endforeach;
if (!empty($ruta)) $sim ="&"; else $sim ="";
?>

<?php if (isset($this->previous)):?>
<a href="<?php echo "/annonces?".$ruta. $sim. "page=".$this->previous;?>" 
	class="nprev" data="<?php echo $this->previous;?>">PRECEDENTE</a>

<?php else: ?>
<!-- <a href="#" class="nprev disabled">PRECEDENTE</a>-->
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)):
?>
<?php if (!empty($ruta)) $sim ="&"; else $sim ="";?>
<a href="<?php echo "/annonces?".$ruta. $sim."page=".$this->next;?>"
	class="nnext" data="<?php echo $this->next;?>">SUIVANTE</a>
<?php else: ?>
<!-- <a href="#" class="nnext disabled">SUIVANTE</a>-->
<?php endif; ?>


