<?php
$ruta = "";
$i=true; 

if (!empty($ruta)) $sim ="&"; else $sim ="";
?>

<?php if (isset($this->previous)):?>
<a href="<?php echo "/detail?".$ruta. $sim. "cod_new=".$this->previous;?>" class="previus border-right" data="<?php echo $this->previous;?>">
	PRECEDENTE
</a>		

<?php else: ?>
<!-- <a href="#" class="nprev disabled">PRECEDENTE</a>-->
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)):
?>
<?php if (!empty($ruta)) $sim ="&"; else $sim ="";?>
<a href="<?php echo "/detail?".$ruta. $sim."cod_new=".$this->next;?>"
	class="suivante" data="<?php echo $this->next;?>">SUIVANTE</a>
<?php else: ?>
<!-- <a href="#" class="nnext disabled">SUIVANTE</a>-->
<?php endif; ?>