
<!-- //magasins // -->
<div id="magasins">
	<div id="magasins-top">
		<h2>
			LE RÉSEAU <br>MOTOEXPERT
		</h2>
		<div class="magasins-right">› 43 Magasins en France</div>
	</div>
	<div id="magasins-bg">
		<div class="magasins-content">
			<p class="magasins-text">Plus de 300 Experts, plus de 40000m²
				d’exposition à votre service.</p>
			<div class="magasins-recherchez">
				<h5>Recherchez votre Magasin</h5>
				<div class="magasins-form">
					<form action="" method="post" name="form1" id="form1">
						<label for="select"></label> <select id="select" name="select">
							<option selected="selected" value="0">Ville</option>
							<option value="1">Ville 1</option>
							<option value="2">Ville 2</option>
							<option value="3">Ville 3</option>
							<option value="4">Ville 4</option>
							<option value="5">Ville 5</option>
							<option value="6">Ville 6</option>
						</select> <input type="submit" value="" id="button" name="button">
					</form>
				</div>
				<img height="104" width="104"
					src="<?=MEDIA_URL ?>images/magasins-img.jpg">

			</div>
			<h6>Des services pertinents pour simplifier la vie des motards</h6>
			<div class="magasins-imgs">
				<img title="accrssoires moto"
					src="<?=MEDIA_URL ?>images/accrssoires-moto.jpg"> <img
					title="fan club" src="<?=MEDIA_URL ?>images/fan-club.jpg"> <img
					title="service rapide"
					src="<?=MEDIA_URL ?>images/service-rapide.jpg">
			</div>
		</div>
	</div>
	<div id="magasins-footer">
		<p>DECOUVREZ LA FRANCHISE ET LES SERVICES</p>
	</div>

</div>
<!-- //occasions // -->
<div id="occasions">
	<div id="occasions-top">
		<h2>OCCASIONS MOTO</h2>
		<div class="occasions-right">› 1311 annonces moto</div>
	</div>
	<div id="occasions-bg">
		<div class="occasions-content">
			<p class="occasions-text">Rechercher une moto d’occasion dans notre
				réseau avec des annonces provenant de toute la France !</p>
			<div class="occasions-recherchez">
				<h5>Recherchez une moto d’occasion</h5>
				<div class="occasions-form">
					<form action="" method="post" name="form1" id="form1">
						<label class="selectlabel1" for="select"></label> <select
							id="select" name="select">
							<option selected="selected" value="0">Marque</option>
							<option value="1">Marque 1</option>
							<option value="2">Marque 2</option>
							<option value="3">Marque 3</option>
							<option value="4">Marque 4</option>
							<option value="5">Marque 5</option>
							<option value="6">Marque 6</option>
						</select> <label class="selectlabel2" for="select"></label> <select
							id="select" name="select">
							<option selected="selected" value="0">Modele</option>
							<option value="1">Modele 1</option>
							<option value="2">Modele 2</option>
							<option value="3">Modele 3</option>
							<option value="4">Modele 4</option>
							<option value="5">Modele 5</option>
							<option value="6">Modele 6</option>
						</select> <input type="submit" value="" id="button" name="button">
					</form>
				</div>
				<img height="104" width="104"
					src="<?=MEDIA_URL ?>images/occasions-img.jpg">
				<p class="deposez">VOIR TOUTES LES ANNONCES</p>

			</div>
			<h6>Des services pertinents pour simplifier la vie des motards</h6>
			<div class="occasions-imgs">
				<img title="accrssoires moto"
					src="<?=MEDIA_URL ?>images/achete-cash.jpg"> <img title="fan club"
					src="<?=MEDIA_URL ?>images/depot-vente.jpg"> <img
					title="service rapide" src="<?=MEDIA_URL ?>images/votre-pa.jpg">
			</div>
		</div>
	</div>
	<div id="occasions-footer">
		<p>DEPOSEZ VOTRE ANNONCE</p>
	</div>

</div>
<!-- // actualite // -->
<div id="actualite">
	<h2>L’ACTUALITÉ MOTO EXPERT</h2>
	<div class="actualite-col3">
		<img height="87" width="87" src="<?=MEDIA_URL ?>images/solde.jpg">
		<h3>Vive les Soldes d’hiver pour s’équiper pas cher !</h3>
		<p>Elles débuteront dans votre magasin Moto Expert officiellement le
			mercredi 11 janvier 2012 à 8 heures</p>
	</div>
	<div class="actualite-col3">
		<img height="87" width="87" src="<?=MEDIA_URL ?>images/people.jpg">
		<h3>Rejoingnez le Fan Club et bénéficiez du prix Fan* -6%
			immédiatement !</h3>
		<p>Rejoingnez le Fan Club et bénéficiez du prix Fan* -6% immédiatement
			!</p>
	</div>
	<div class="actualite-col3right">
		<img height="87" width="87" src="<?=MEDIA_URL ?>images/house.jpg">
		<h3>Fermeture du magasin de Saint-Quentin</h3>
		<p>Le magasin est dorénavant fermé. Nous vous informerons dès sa
			réouverture.</p>
	</div>
	<div>
		<a class="actualite-link" href="#">› VOIR TOUTES LES ACTUALITES</a>
	</div>
</div>


<!-- SLIDE -->
            <!-- // Slider // -->
            <div id="sliders">
                        <!-- start -->
                        <ul class="bjqs">
                          <li><img src="<?=MEDIA_URL ?>images/slider/1.jpg" title=""></li>
                          <li><img src="<?=MEDIA_URL ?>images/slider/2.jpg" title=""></li>
                          <li><img src="<?=MEDIA_URL ?>images/slider/3.jpg" title=""></li>
                          <li><img src="<?=MEDIA_URL ?>images/slider/4.jpg" title=""></li>
                        </ul>
                        <!-- end -->
            </div>
             <!-- // Slider // -->

<!-- FIN SLIDE -->




<div id="inscrire">
	<div class="inscrire-left">
		Restez informé de toute l’actualité du site en vous<br> inscrivant à
		la newsletter :<a href="#">MENTIONS LEGALES</a>
	</div>
	<div class="inscrire-right">
		<form action="" method="post" name="form2" id="form2">
			<input type="text" placeholder="Votre adresse email" id="textfield"
				name="textfield"> <input type="submit" value="S’INSCRIRE"
				id="button2" name="button2">
		</form>
		<a title="facebook" href="http://www.facebook.com">SUIVEZ NOUS</a>
	</div>
</div>


