<script>
$(function() {
      $('#magasin').change(function() {
            $('#magasin').submit();
      });
});
</script>
<!-- //magasins // -->
<div id="magasins">
	<div id="magasins-top">
     <div class="magasins-tops"></div>
		<h2>
			LE RÉSEAU <br>MOTOEXPERT
		</h2>
		<div class="magasins-right">› <?= $this->countMagasin['magasin'];?> Magasins en France</div>
	</div>
	<div id="magasins-bg">
		<div class="magasins-content">
			<p class="magasins-text">Plus de 300 Experts, plus de 40000m²
				d’exposition à votre service.</p>
			<div class="magasins-recherchez">
				<h5>Recherchez votre Magasin</h5>
				<div class="magasins-form">
                                    <form action="magasin" method="get" name="magasin" id="magasin" onchange="fo">
						<label for="select"></label> 
                                                    <?= $this->formMagasin->magasin?>
						<input type="submit" value="" id="button" name="button">
					</form>
				</div>
				<img height="104" width="104" src="<?=MEDIA_URL ?>images/magasins-img.jpg">
                                <p class="visual">VISUALISEZ TOUS LES MAGASINS</p>
			</div>
			<h6>Des services pertinents pour simplifier la vie des motards</h6>
			<div class="magasins-imgs">
                                <a href="/service"><img title="accrssoires moto" src="<?=MEDIA_URL ?>images/accrssoires-moto.jpg"></a>
                                <a href="/franchise/carte-fidelite"><img title="fan club" src="<?=MEDIA_URL ?>images/fan-club.jpg"></a>
                                <a href="/franchise/service-rapide"><img title="service rapide" src="<?=MEDIA_URL ?>images/service-rapide.jpg"></a>
			</div>
		</div>
	</div>
	<div id="magasins-footer">
     <div class="magasins-botton"></div>
		<a class="actualite-linkof" href="/franchise"><p>DECOUVREZ LA FRANCHISE ET LES SERVICES</p></a>
	</div>

</div>
<!-- //occasions // -->
<div id="occasions">
	<div id="occasions-top">
    <div class="occasions-tops"></div>
		<h2>OCCASION MOTO</h2>
		<div class="occasions-right">› <?= $this->totalAnuncio['totalAnnounce'];?> annonces moto</div>
	</div>
	<div id="occasions-bg">
		<div class="occasions-content">
			<p class="occasions-text">Rechercher une moto d’occasion dans notre
				réseau avec des annonces provenant de toute la France !</p>
			<div class="occasions-recherchez">
				<h5>Recherchez une moto d’occasion</h5>
				<div class="occasions-form">
					<form action="annonces" method="get" name="form1" id="form1">
						<label class="selectlabel1" for="select"></label> 
						<?=$this->form->marque?>
						
						 <label class="selectlabel2" for="select"></label> 
						 <?=$this->form->modele?> 
						<input type="submit" value="" id="button" name="button">
					</form>
				</div>
				<img height="104" width="104"
					src="<?=MEDIA_URL ?>images/occasions-img.jpg">
                                <p class="deposez"><a href="/annonces" >VOIR TOUTES LES ANNONCES</a></p>

			</div>
			<h6>Des services pertinents pour simplifier la vie des motards</h6>
			<div class="occasions-imgs">
                            <a href="/franchise/occasion-moto"><img title="achete cash" src="<?=MEDIA_URL ?>images/achete-cash.jpg"> </a>
                            <a href="/franchise/occasion-moto"><img title="depot vente" src="<?=MEDIA_URL ?>images/depot-vente.jpg"> </a>
                            <a href="/franchise/occasion-moto"><img title="votre pa" class="nomargin" src="<?=MEDIA_URL ?>images/votre-pa.jpg"></a>
			</div>
		</div>
	</div>
	<div id="occasions-footer">
    <div class="occasions-botton"></div>
            <?php if ($this->authData){?>
                <a class="actualite-linkof" href="/compte/annonce-publier"><p>DEPOSEZ VOTRE ANNONCE</p></a>
            <?php } else {?>
                <a class="actualite-linkof" href="/login"><p>DEPOSEZ VOTRE ANNONCE</p></a>
            <?php } ?>
            
		
	</div>

</div>
<!-- // actualite // -->
<div id="actualite">
	<h2>L’ACTUALITÉ MOTO EXPERT</h2>
	
         <?php
            $config = Zend_Registry::get('config');
            $z=0;
            foreach ($this->news  as $news) :
             $z++;
             $ruta = $config->app->photoNews.$news['image_1'];
         ?>
        <?php  if($z==1):  ?>
	<div class="actualite-col3   actualite-col1">
        <?php endif; if($z==2): ?>
        <div class="actualite-col3"> 
        <?php endif; if($z==3): ?>
        <div class="actualite-col3right">    
        <?php endif;  ?> 
		<img height="87" width="87" src="<?=$ruta;?>">
		<h3><?= $news['titre']?></h3>
		<p><?= $news['texte_1']?></p>
	</div>
	
        <?php
        endforeach;
        ?>
        
        
	<div>
		<a class="actualite-link" href="/news">› VOIR TOUTES LES ACTUALITES</a>
	</div>
</div>
<!-- SLIDE -->
            <!-- // Slider // -->
            <div id="sliders">
                        <!-- start -->
                        <ul class="swipe-wrap">
                          <?php
                            $config = Zend_Registry::get('config');
                            
      
                           foreach ($this->slider as $slider) :
                               $ruta = $config->app->photoNews.$slider['value'];
                           
                          ?>
                          <li><img src="<?=$ruta; ?>" title=""></li>
                          <?php
                          endforeach;
                          ?>
                        </ul>
                        <!-- end -->
            </div>
             <!-- // Slider // -->

<!-- FIN SLIDE -->




<div id="inscrire">
	<!--<div class="inscrire-left">
		<p>Restez informé de toute l’actualité du site en vous inscrivant à la newsletter :</p>
                <a href="/mentions">MENTIONS LEGALES</a>
	</div>
	<div class="inscrire-right">
		<form action="" method="post" name="form2" id="form2">
			<input type="text" placeholder="Votre adresse email" id="textfield"
				name="textfield"> <input type="submit" value="S’INSCRIRE"
				id="button2" name="button2">
		</form>
                
		<a title="facebook" href="http://www.facebook.com">SUIVEZ NOUS</a>
	</div>-->
</div>
<script src="<?php echo MEDIA_URL ?>js/swipe.js"></script>
<script>
$(document).ready(function() {
	Slider = $('#sliders').Swipe({
		auto: 7000,
		continuous: true
	}).data('Swipe');

	//$('.next').on('click', Slider.next);
	//$('.prev').on('click', Slider.prev);
});
</script>
<script src="<?php echo MEDIA_URL ?>js/marque-back.js"></script>