<div id="footer">
        	<div class="footer-logo"><img height="97" width="264" src="<?=MEDIA_URL ?>images/footer-logo.png"></div>
            <div class="footer-col1">
              <a href="login">DÉPOSEZ VOTRE ANNONCE GRATUITE</a><p></p>
              <a href="annonces">MOTOS D’OCCASIONS</a><p></p>
            </div>
          <div class="footer-col2">
	          <h3>LES SERVICES MOTO EXPERT</h3>
              <form action="magasin" method="get" name="magasin" id="magasin">
						<label for="select"></label> 
                                                    <?= $this->formMagasin->magasin?>
						<input type="submit" value="" id="button" name="button">
            </form>
              
          </div>
          <div class="footer-col3">
          	<h3>LES SERVICES MOTO EXPERT</h3>
              <a href="annonces">Occasion moto</a>
              <a href="#">Service rapide</a>
              <a href="#">Fan Club</a>
          </div>
          <div class="footer-col4">
          	<a href="#">L’ACTU</a>
            <a href="#">CONTACTS</a>         
          </div>
          
          <div class="copy">&copy; 2014 MOTOEXPERT   Réalisation : Infra - Tous droits réservé</div>
        </div>