<div id="footer">
        	<div class="footer-logo"><img height="97" width="264" src="<?=MEDIA_URL ?>images/footer-logo.png"></div>
            <div class="footer-col1">
              <a href="#">DÉPOSEZ VOTRE ANNONCE GRATUITE</a><p></p>
              <a href="#">MOTOS D’OCCASIONS</a><p></p>
            </div>
          <div class="footer-col2">
	          <h3>LES SERVICES MOTO EXPERT</h3>
              <form action="" method="post" name="form3" id="form3">
                                <label for="select"></label>
                                <select id="select" name="select">
                                	<option selected="selected" value="0">Ville</option>
                                    <option value="1">Ville 1</option>
                                    <option value="2">Ville 2</option>
                                    <option value="3">Ville 3</option>
                                    <option value="4">Ville 4</option>
                                    <option value="5">Ville 5</option>
                                    <option value="6">Ville 6</option>
                                </select> 
                                <input type="submit" value="" id="button" name="button">
                              </form>
              
          </div>
          <div class="footer-col3">
          	<h3>LES SERVICES MOTO EXPERT</h3>
              <a href="#">Occasion moto</a>
              <a href="#">Service rapide</a>
              <a href="#">Fan Club</a>
          </div>
          <div class="footer-col4">
          	<a href="#">L’ACTU</a>
            <a href="#">CONTACTS</a>         
          </div>
          
          <div class="copy">&copy; 2014 MOTOEXPERT   Réalisation : Infra - Tous droits réservé</div>
        </div>