<? $levels = array('debug', 'info', 'success', 'warning', 'error'); ?>
    <? if ($this->fmsgs) { ?>
    <div id="fmsgs" style='padding-top:10px; padding-bottom: 0px'>
    <? 
    	foreach ($this->fmsgs as $msg): ?>
        <div class="alert alert-success <?= $msg->level == 'debug' ? 'error block-message' : $msg->level ?>">            
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <i class="icon-ok-sign"></i>
            <?= $msg->message ?>
        </div>            
    <? endforeach; ?>
    </div> 
    <? } ?>



