<div id="sidebar-nav">
	<ul id="dashboard-menu">
		<li class="active">
			<div class="pointer">
				<div class="arrow"></div>
				<div class="arrow_border"></div>
			</div> <a href="/admin/panel"> <i class="icon-home"></i> <span>Inicio</span>
		</a>
		</li>

		<li><a href="/admin/usuario"> <i class="icon-group"></i> <span>Usuarios</span>

		</a></li>
		<li><a href="#" class="dropdown-toggle"> <i class="icon-music"></i> <span>RBT</span>
				<i class="icon-chevron-down"></i>
		</a>
			<ul class="submenu">
				<li><a href="/admin/contenido">Buscar</a>
				</li>
				<li><a href="/admin/contenido/cargar">Cargar </a>				
				</li>				
				<li><a href="/admin/contenido/pendientes">Pendientes </a>
				</li>
				<li><a href="/admin/contenido/ordenar">Ordenar </a>
				</li>
			</ul>
		</li>
		
		<li><a href="#" class="dropdown-toggle"> <i class="icon-edit"></i> <span>Items</span>
				<i class="icon-chevron-down"></i>
		</a>
			<ul class="submenu">
				<li><a href="/admin/categoria">Categorias</a>
				</li>
				<li><a href="/admin/genero">Genero Musical</a>
				</li>
				<li><a href="/admin/help">Ayuda / Faqs</a>
				</li>				
			</ul>
		</li>
		
		<li><a href="#" class="dropdown-toggle"> <i class="icon-signal"></i> <span>Reportes</span>
				<i class="icon-chevron-down"></i>
		</a>
		
		<ul class="submenu">				
				<li>
				<a href="/admin/reportes/alta-usuarios">Alta Usuarios</a>
				<a href="/admin/reportes/baja-usuarios">Baja Usuarios</a>
				<a href="/admin/reportes/ventas">Ventas</a>
				</li>				
			</ul>			
		</li>

		<li><a href="#"> <i class="icon-cog"></i> <span>Mi
					cuenta</span>
		</a></li>

	</ul>
</div>
