<div id="header">
	<div id="logo">
		<a
			title="MOTO EXPERT - Réseau de magasins spécialisés moto, annonces moto occasion, accessoires moto"
			href="index.html"><img height="113" width="308"
			alt="MOTO EXPERT - Réseau de magasins spécialisés moto, annonces moto occasion, accessoires moto"
			src="<?=MEDIA_URL ?>images/logo.png">
		</a>
	</div>
	<div id="header-right">
		<div class="header-top">
			<a href="#">ACTUALITE RESEAU</a> - <a href="#">NEWSLETTER</a> <a
				class="nomcompte" href="#">MON COMPTE</a>
		</div>

	</div>
	<div class="header-menu">
		<ul>
			<li><a class="menu-red" href="#">ACCUEIL</a>
			</li>
			<li><a class="menu-yellow" href="#">OCCASION MOTO</a>
			</li>
			<li><a class="menu-blue" href="#">FRANCHISE ET SERVICES</a>
			</li>
			<li class="noborder"><a class="menu-green" href="#">CONTACT</a>
			</li>
		</ul>

	</div>
</div>
