<!DOCTYPE >
<html lang="en-US">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<link href="<?php echo MEDIA_URL ?>responsive.css" type="text/css"	rel="stylesheet" />
<link href="<?php echo MEDIA_URL ?>style2.css" type="text/css"	rel="stylesheet">

<!-- fonts -->
<link type="text/css" rel="stylesheet"
	href="http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700">
	
<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="<?php echo MEDIA_URL ?>js/bjqs-1.3.min.js"></script>
<script class="secret-source">
        jQuery(document).ready(function($) {          
          $('#sliders').bjqs({       
          
			// animation values
            width    : 985,
			height   : 395, 			
			animtype : 'fade', // accepts 'fade' or 'slide'
			animduration : 450, // how fast the animation are
			animspeed : 4000, // the delay between each slide
			automatic : true, // automatic
			
			// control and marker configuration
			showcontrols : true, // show next and prev controls
			centercontrols : true, // center controls verically
			nexttext : '<img src="<?=MEDIA_URL?>images/slider/next.png" />', 
			prevtext : '<img src="<?=MEDIA_URL?>images/slider/prev.png" />', 
			showmarkers : true, // Show individual slide markers
			centermarkers : true, // Center markers horizontally
			
			// interaction values
			keyboardnav : true, // enable keyboard navigation
			hoverpause : true, // pause the slider on hover
			
			// presentational options
			usecaptions : true, // show captions for images using the image title tag
			randomstart : true, // start slider at random slide
			responsive : true // enable responsive capabilities (beta)
			
					  });
					  
					});
</script>	


<title>MOTO EXPERT - Réseau de magasins spécialisés moto, annonces moto
	occasion, accessoires moto</title>

</head>

<body>
<div id="wrapper">


	<?= $this->render('_topbar.phtml');?>	
	<div class="content">		
			<?=$this->layout()->content?>
	</div>
	<?= $this->render('_footer.phtml');?>

</div>
</body>
</html>
