<!DOCTYPE >
<html lang="en-US">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<link href="<?php echo MEDIA_URL ?>style2.css" type="text/css"	rel="stylesheet">
<link href="<?php echo MEDIA_URL ?>responsive.css" type="text/css"	rel="stylesheet" />
	
<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="<?php echo MEDIA_URL ?>js/jquery.lightbox_me.js" type="text/javascript" charset="utf-8"></script>

<!-- fonts -->
<link type="text/css" rel="stylesheet"
	href="http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700">

<title>MOTO EXPERT - Réseau de magasins spécialisés moto, annonces moto
	occasion, accessoires moto</title>

</head>

<body>
<div id="wrapper">


	<?= $this->render('_topbar.phtml');?>	
	<div class="content">		
			<?=$this->layout()->content?>
	</div>
	<?= $this->render('_footer.phtml');?>

</div>
</body>
</html>
