<div id="pad-wrapper">                
                <div class="table-wrapper products-table section">
                    <div class="row-fluid head">
                        <div class="span10">
                            <h4>Usuarios : </h4>
                        </div>
                        <div class="span2">
                        <a class="btn-flat success new-product" href="/admin/usuario/crear">+ Nuevo Usuario</a>
                        </div>
                        
                    </div>
                    

                    <div class="row-fluid filter-block">
                        <div class="pull-right">
                        <form method="get" action="/admin/usuario">
                            <div class="ui-select">
                                <?php echo $this->form->flag?>
                            </div>
                            <?php echo $this->form->busqueda?>
                        </form>                            
                        </div>
                    </div>

                    <div class="row-fluid">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th class="span2">
                                        ID
                                    </th>
                                    <th class="span2">
                                        Empresa
                                    </th>
                                    <th class="span3">
                                        Tipo Usuario
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Usuario
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Correo Electrónico
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Teléfono
                                    </th>
                                    <th class="span3">
                                        <span class="line"></span>
                                        Acciones
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- row -->
                                <?php foreach ($this->empresas as $item): ?>
                                <tr>
                                    <td>
                                        <a href="#"><?=$item['iduser_empresa'] ?></a>
                                    </td>
                                    <td>
                                        <?=$item['nombre'] ?>
                                    </td>
                                    <td>
                                        <?php echo ($item['tipousuario']=='1')?'SuperAdmin':(($item['tipousuario']=="2")?'Empresa':'Operador') ?>
                                    </td>
                                    <td>
                                        <a href="#<?//=$item['iduser_empresa'] ?>"><?=$item['usuario'] ?></a>
                                    </td>
                                    <td>
                                        <?=$item['correo_electronico'] ?>
                                    </td>
                                    <td>
                                        <?=$item['telefono'] ?>
                                    </td>
                                    <td>                                        
                                        <a class="#" href="/admin/usuario/cambiar-clave/cod/<?=$item['iduser_empresa'] ?>"> Cambiar clave </a>                                    
                                    </td>
                                </tr>
                                <?php endforeach; ?>                                
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- end products table -->

                
            </div>