<?php
	    $datos = '';
	    $nom = '';
	    $prenom = '';
	    $adresse = '';
	    $code_postal = '';
	    $ville = '';
	    $portable = '';
	    $email = '';
	    $pass = '';
	    $passr = '';
?>

<script>
 
  var dispatchpopup = function(){  
    $('#my_lightbox').lightbox_me({
      centered: true,
      onLoad: function() {
        $('#my_lightbox_text').html("Stuff");
      }
    });
  }
  var nuevo = function(){
	  <?php if ($this->error) {?>  
	    $('#my_lightbox').lightbox_me({
	      centered: true,
	      onLoad: function() {
	        $('#my_lightbox_text').html("Stuff");
	      }
	    });
	    <?php
	    $datos = $this->data;
	    $nom = ($datos['nom'] and !empty($datos['nom']))?TRUE:FALSE;
	    $prenom = ($datos['prenom'] and !empty($datos['prenom']))?TRUE:FALSE;
	    $adresse = ($datos['adresse'] and !empty($datos['adresse']))?TRUE:FALSE;
	    $code_postal = ($datos['code_postal'] and !empty($datos['code_postal']))?TRUE:FALSE;
	    $ville = ($datos['ville'] and !empty($datos['ville']))?TRUE:FALSE;
	    $portable = ($datos['portable'] and !empty($datos['portable']))?TRUE:FALSE;
	    $email = ($datos['email'] and !empty($datos['email']))?TRUE:FALSE;
	    $pass = ($datos['pass'] and !empty($datos['pass']))?TRUE:FALSE;
	    $passr = $datos['passred'];
	    if ($pass != $passr)
	    	$pass = false;

} ?>
	  }
</script>
<script src="<?=MEDIA_URL ?>js/jquery.validate.js"></script>
<script>
$.validator.setDefaults({
	submitHandler: function() { $( "#formRegister" ).submit();}
});

$().ready(function() {
	// validate the comment form when it is submitted


	// validate signup form on keyup and submit
	$("#formRegister").validate({
		rules: {
			nom: "required",
			prenom: "required",
			username: {
				required: true,
				minlength: 2
			},
			pass: {
				required: true,
				minlength: 5
			},
			passred: {
				required: true,
				minlength: 5,
				equalTo: "#pass"
			},			
			tel: {
				required: true,
				minlength: 5
			},

			email: {
				required: true,
				email: true
			},
			agree: "required"
		},
		messages: {
			nom: "Please enter your firstname",
			prenom: "Please enter your lastname",

			tel: {
				required: "Please provide a telephone",
				minlength: "Your telephone must be at least 5 characters long"
			},
			pass: {
				required: "Please provide a password",
				minlength: "Your password must be at least 5 characters long"
			},
			passred: {
				required: "Please provide a password",
				minlength: "Your password must be at least 5 characters long",
				equalTo: "Please enter the same password as above"
			},
			email: "Please enter a valid email address",
			agree: "Please accept our policy"
		}
	});



});
</script>


<div id="content" class="paddin30"> 
        	<div id="content-top">
            
                            <div class="top-left"><span>VOTRE COMPTE</span></div>
        	</div>
       	  
          <!-- //*** LOGIN  //-->
          <div id="login-c">
          	<div class="col2 align-left">
           	  <div class="login  align-right">
              	<form id="form2" name="form2" method="post" action="/auth" style="margin: 0">
				<div class="login-content">
					<h3>VOUS POSSÉDEZ DÉJÀ UN COMPTE?</h3>
<label for="textfield4">E-mail * :</label> 
<input type="text" name="email" class="inputcol2" id="email" required="required"/> 
<label for="textfield5">Mot de passe :</label> 
<input type="password" name="passe" class="inputcol2" id="passe" required="required"/>

<div class="passe">
<a href="#">Mot de passe oublié ? </a>
</div>
					
				</div>
				<input name="ENVOYER" type="submit" id="ENVOYER" value="ENVOYER" />
				</form>
                </div>
          	</div>
          	<div class="col2-lo align-left">
          	  <div class="login  align-left ">
              	<div class="login-content">
                
               	  <h3>VOUS SOUHAITEZ CRÉER UN COMPTE?</h3>
                  <p>Il vous permettra e déposer et gérer vos annonces moto<br>
                    <br>
                  </p>
                  <p>MOTO EXPERT s'engage à sécuriser vos informations et à les garder strictement confidentielles </p>
 
                </div>
           
                 <a href="#" onClick="dispatchpopup();" class="btn-submit" >CREER UN COMPTE</a>
                          

                
            </div>
          </div>
          
          </div>
 
          </div>

<div id="my_lightbox">
  <div id="wrapper-form">
    	<div id="new-form">
        	<div id="new-navigation"><a href="#" class="new-prev" onClick="$('#my_lightbox').trigger('close');">RETOUR</a>
        	<p>VOS COORDONNÉES</p> </div>
           
        <form name="formRegister"  class="cmxform"  id="formRegister" method="post" action="">
        <p><?php echo ($this->error)?"S'il vous plaît vérifier vos informations":''?></p>
        	<p class="in-radio"> Civilité 
        	<input type="radio" name="civilite" id="radio" value="Mme" checked="checked"/>
              <label for="radio">Mme</label>
            <input type="radio" name="civilite" id="radio" value="Mlle"/>
              <label for="radio">Mlle</label>
            <input type="radio" name="civilite" id="radio" value="M"/>
              <label for="radio">Mr</label>
            </p>
          <p><input name="nom" type="text" placeholder="Nom" required="required" value="<?php echo ($nom)?$datos["nom"]:'';?>" /></p>
          <p><input name="prenom" type="text" placeholder="Prénom" required="required" value="<?php echo ($prenom)?$datos["prenom"]:'';?>"/></p>
          <p><input name="adresse" type="text" placeholder="Adresse" required="required" value="<?php echo ($adresse)?$datos["adresse"]:'';?>"/></p>
          <p><input name="code_postal" type="text" placeholder="Code Postal" required="required" value="<?php echo ($code_postal)?$datos["code_postal"]:'';?>"/></p>
          
          
          <p>
            <select name="ville" id="ville" > 
                <option value="fr">France</option>
                <option value="al">Allemagne</option>
                <option value="su">Suisse</option>
                <option value="be">Belgique</option>
            </select> 
              
          </p>
          
          <p><input name="pays" type="text" placeholder="Pays"></p>
          <p><input name="tel" type="text" placeholder="Téléphone"></p>
          <p><input name="portable" type="text" placeholder="Mobile" value="<?php echo ($portable)?$datos["portable"]:'';?>"/></p>
          <p><span class="in-text">Je désire être tenu au courant de l’actualité et des nouveautés du site Moto Expert</span>
              <input name="mailing" type="checkbox" value=""/> 
          </p>
            
            <div id="new-navigation"><span>VOS INFORMATIONS DE CONNEXION</span> </div>
            <p>
            <input name="email" type="text" placeholder="Votre adresse Email" required="required" value="<?php echo ($email)?$datos["email"]:'';?>">
            </p>
          	<p class="new-p14">Vous servira d’identifiant de connexion</p>
            <p><input name="pass" id="pass" type="password" placeholder="Mot de Passe" required="required"/></p>
   		    <p><input name="passred" id="passred" type="password" placeholder="Confirmer le mot de Passe" required="required"/></p>
           
            <p><input name="" type="reset" value="ANNULER"></p>
            <p><input name="" type="submit" value="ENREGISTRER"></p>
            
        </form>
    	</div>
	  
      
	</div>
</div>