<script>
  var dispatchpopup = function(){  
    $('#my_lightbox').lightbox_me({
      centered: true,
      onLoad: function() {
        $('#my_lightbox_text').html("Stuff");
      }
    });
  }
</script>

<div id="content" class="paddin30"> 
        	<div id="content-top">
            
                            <div class="top-left"><span>VOTRE COMPTE</span></div>
        	</div>
       	  
          <!-- //*** LOGIN  //-->
          <div id="login-c">
          	<div class="col2 align-left">
           	  <div class="login  align-right">
              	<form id="form2" name="form2" method="post" action="/auth" style="margin: 0">
				<div class="login-content">
					<h3>VOUS POSSÉDEZ DÉJÀ UN COMPTE?</h3>
<label for="textfield4">E-mail * :</label> 
<input type="text" name="email" class="inputcol2" id="email" required="required"/> 
<label for="textfield5">Mot de passe :</label> 
<input type="password" name="passe" class="inputcol2" id="passe" required="required"/>

<div class="passe">
<a href="#">Mot de passe oublié ? </a>
</div>
					
				</div>
				<input name="ENVOYER" type="submit" id="ENVOYER" value="ENVOYER" />
				</form>
                </div>
          	</div>
          	<div class="col2-lo align-left">
          	  <div class="login  align-left ">
              	<div class="login-content">
                
               	  <h3>VOUS SOUHAITEZ CRÉER UN COMPTE?</h3>
                  <p>Il vous permettra e déposer et gérer vos annonces moto<br>
                    <br>
                  </p>
                  <p>MOTO EXPERT s'engage à sécuriser vos informations et à les garder strictement confidentielles </p>
 
                </div>
           
                 <a href="#" onClick="dispatchpopup();" class="btn-submit" >CREER UN COMPTE</a>
                          

                
            </div>
          </div>
          
          </div>
 
          </div>

<div id="my_lightbox">
  <div id="wrapper-form">
    	<div id="new-form">
        	<div id="new-navigation"><a href="#" class="new-prev" onClick="$('#my_lightbox').trigger('close');">RETOUR</a><p>VOS COORDONNÉES</p> </div>
           
        <form name="formRegister" method="post" action="">
        	<p class="in-radio"> Civilité 
        	<input type="radio" name="civilite" id="radio" value="Mme" checked="checked"/>
              <label for="radio">Mme</label>
            <input type="radio" name="civilite" id="radio" value="Mlle"/>
              <label for="radio">Mlle</label>
            <input type="radio" name="civilite" id="radio" value="Mr"/>
              <label for="radio">Mr</label>
            </p>
          <p><input name="nom" type="text" placeholder="Nom" required="required"/></p>
          <p><input name="prenom" type="text" placeholder="Prénom" required="required"/></p>
          <p><input name="adresse" type="text" placeholder="Adresse" required="required"/></p>
          <p><input name="code_postal" type="text" placeholder="Code Postal" required="required"/></p>
          <p><input name="ville" type="text" placeholder="Ville" required="required" /></p>
          <p><input name="pays" type="text" placeholder="Pays"></p>
          <p><input name="tel" type="text" placeholder="Téléphone"></p>
          <p><input name="portable" type="text" placeholder="Mobile" required="required"/></p>
          <p><span class="in-text">Je désire être tenu au courant de l’actualité et des nouveautés du site Moto Expert</span>
              <input name="mailing" type="checkbox" value=""/> 
          </p>
            
            <div id="new-navigation"><span>VOS INFORMATIONS DE CONNECTION</span> </div>
            <p>
            <input name="email" type="text" placeholder="Votre adresse Email" required="required">
            </p>
          	<p class="new-p14">Vous servira d’identifiant de connection</p>
            <p><input name="pass" type="password" placeholder="Mot de Passe" required="required"/></p>
   		    <p><input name="passred" type="password" placeholder="Confirmer le mot de Passe" required="required"/></p>
           
            <p><input name="" type="reset" value="ANNULER"></p>
            <p><input name="" type="submit" value="ENREGISTRER"></p>
            
        </form>
    	</div>
	  
      
	</div>
</div>