<link href="<?=MEDIA_URL ?>css/flexslider.css" rel="stylesheet">

<div id="content" class="paddin30"> 
        	<div id="content-top">
            
                            <div class="top-left">MOTO EXPERT <br /><span>MOTOS D'OCCASION</span></div>
        	</div>
       	  <div id="navi-fiche">
          	  <a href="#" class="previus">RETOUR A LA LISTE D'ANNONCES </a>

            
            <div class="align-right text-right">
            	<a href="#" class="previus border-right">PRECEDENTE</a><a href="" class="suivante">SUIVANTE</a>
            </div>

          </div>
          <!-- //*** DETAILS  //-->
          <div id="details">
          	<div class="col2 align-left">
            	<div class="gallery">
                   <DIV class="flexslider" id="imageitems">
                        <UL class="slides">
                          <LI><IMG   alt="" src="<?=MEDIA_URL ?>images/product/1.jpg"></LI>
                          <LI><IMG   alt="" src="<?=MEDIA_URL ?>images/product/2.jpg"></LI>
                          <LI><IMG   alt="" src="<?=MEDIA_URL ?>images/product/3.jpg"></LI>
                          <LI><IMG   alt="" src="<?=MEDIA_URL ?>images/product/4.jpg"></LI>
                          <LI><IMG   alt="" src="<?=MEDIA_URL ?>images/product/5.jpg"></LI>
                          <LI><IMG   alt="" src="<?=MEDIA_URL ?>images/product/6.jpg"></LI>
                          <LI><IMG   alt="" src="<?=MEDIA_URL ?>images/product/7.jpg"></LI>
                          <LI><IMG   alt="" src="<?=MEDIA_URL ?>images/product/8.jpg"></LI>
                        </UL>
                      </DIV>
                   
                  
                      <DIV class="flexslider" id="carouselslider">
                        <UL class="slides">
                          <LI><IMG alt="" src="<?=MEDIA_URL ?>images/product/t1.jpg"></LI>
                          <LI><IMG alt="" src="<?=MEDIA_URL ?>images/product/t2.jpg"></LI>
                          <LI><IMG alt="" src="<?=MEDIA_URL ?>images/product/t3.jpg"></LI>
                          <LI><IMG alt="" src="<?=MEDIA_URL ?>images/product/t4.jpg"></LI>
                          <LI><IMG alt="" src="<?=MEDIA_URL ?>images/product/t5.jpg"></LI>
                          <LI><IMG alt="" src="<?=MEDIA_URL ?>images/product/t6.jpg"></LI>
                          <LI><IMG alt="" src="<?=MEDIA_URL ?>images/product/t7.jpg"></LI>
                          <LI><IMG alt="" src="<?=MEDIA_URL ?>images/product/t8.jpg"></LI>

                        </UL>
                   
            </DIV>
                </div>
                
               </div>
               
   
          	<div class="col2 align-right">
            	<div class="partager"><a href="http://www.facebook.com" target="_blank"><img src="<?=MEDIA_URL ?>images/p-facebook.jpg" width="26" height="26" /></a><a href="http://www.twitter.com" target="_blank"><img src="<?=MEDIA_URL ?>images/p-twitter.jpg" width="26" height="26" /></a>Partager</div>
                <h2>DUCATI SS900</h2>
                <div class="price">4200 €</div>
                <div class="col2  align-left">
                <a href="#" class="visuel visu-gara">CONTRÛLE VISUEL</a> <a href="#" class="garantie visu-gara">GARANTIE </a>
                </div>
                 <div class="col2  align-left">
                 	<p>Annonce 4902113260000</p>
                    <p>Publiée le 01/02/14</p>
                    <p><br/></p>
                    <p><strong>Marque</strong> : Ducati</p>
                    <p><strong>Modèle </strong>: SS</p>
                    <p><strong>Catégorie</strong> : Sportives</p>
                    <p><strong>Couleur</strong> : rouge</p>
                    <p><strong>Cylindrée</strong> : 900 cm3</p>
                    <p><strong>Km</strong> : 37796</p>
                    <p><strong>Année</strong> : 1998</p>
                    <p><strong>Magasin </strong>: MOTO EXPERT LA ROCHE/YON</p>
                    <p><strong>Département</strong> : 85</p>
                    <hr />
                    <p><strong>Descriptif</strong> :</p>
                   <p>Entretien à jour sur facture. nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in</p>
                    <p></p>
 
              </div>
              </div>
                          
               
               
               <div style="width:100%; height:10px; clear:both"></div>
               
               
               
               
               
               
               
               
               
               
               <div class="col2 align-left"> 
            	<div class="subtitle">
                	<div class="icontitle icon-contact">CONTACTEZ DIRECTEMENT LE MAGASIN</div>
              </div>
              <div class="top-left">MOTO EXPERT <br /><span>METZ </span></div>
             
              <div class="col2 align-left margin-top">
              	<div class="col21"><img src="<?=MEDIA_URL ?>images/map.jpg" width="222" height="119" /></div>
                <div class="col22">
                	<div class="subtitle2">
                		PLAN INTERACTIF 
              		</div>
                    <p>ZAC Rieucoulon 60 Rue Pierre et Marie Curie 34430 SAINT JEAN DE VEDAS</p>
                	<p>Tél. : 02 51 18 83</p>
                    <p>Fax : 0251 05 18 57 </p>
                    <h3>HORAIRES D'OUVERTURE</h3>
                    <p>Lundi : 14h - 19h</p>
                    <p>du Mardi au Samedi : 9h30 - 12h / 14h - 19h</p>
                </div>
              
              </div>
              
              
            
            </div>
              
              <div class="col2  align-right">
              <div class="col2  align-left">
                 <div class="subtitle">
                	<div class="icontitle icon-envoyer">ENVOYER UN MAIL</div>
                 </div>
              <form id="form1" name="form1" method="post" action="">
              
              
                  	<label for="textfield">Nom* :</label>
                    <input type="text" name="textfield" id="textfield" />
                 
                 
                 	<label for="textfield2">Prénom* :</label>
                    <input type="text" name="textfield2" id="textfield2" />
                <label for="textfield3">Adresse :</label>
                    <input type="text" name="textfield3" id="textfield3" />
                    <label for="textfield4">Code postal* :</label>
                    <input type="text" name="textfield4" class="inputcol2" id="textfield4" />
                    
                    <label for="textfield5">Ville :</label>
                    <input type="text" name="textfield5" class="inputcol2" id="textfield5" />
                    <label for="textfield6">Téléphone : </label>
                    <input type="text" name="textfield6" id="textfield6" />
                    <label for="textfield7">E-mail :*</label>
                    <input type="text" name="textfield7" id="textfield7" />
                    
                    <label for="textarea">Message : </label>
                <textarea name="textarea" id="textarea" cols="45" rows="5"></textarea>
                    <div class="fomrinfo">
                    	<span>Veuillez saisir les lettres de limage dans le champ situé sous l'image en respectant les majuscules et les minuscules.</span>
                    <div class="captcha"><img src="<?=MEDIA_URL ?>images/captcha.jpg" width="126" height="86" /></div>
                   <div class="condition">
                   	<input name="" type="checkbox" value="" />En cochant cette case, je souhaite recevoir la newsletter Moto Expert
                   
                   </div>
                    
                    <input name="ENVOYER" type="submit" id="ENVOYER" value="ENVOYER" />
                    
                    </div>

              </form>
              </div>  
                 
                
                
            </div>
          </div>
          
          
          
          
          
          <div id="navi-fiche">
          	  <a href="#" class="previus">RETOUR A LA LISTE D'ANNONCES </a>

           
            <div class="align-right">
            	<a href="#" class="previus border-right">PRECEDENTE</a><a href="" class="suivante">SUIVANTE</a>
            </div>

          </div>
          </div>
          

<script src="<?php echo MEDIA_URL ?>js/jquery.flexslider-min.js" type="text/javascript"></script>          

<script type="text/javascript">
jQuery(window).load(function() {

  jQuery('#carouselslider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: true,
    slideshow: true,
    itemWidth: 110,
    itemMargin:0,
    asNavFor: '#imageitems'
  });
   
  jQuery('#imageitems').flexslider({
    animation: "fade",
	directionNav: false,
    controlNav: false,
    animationLoop: true,
    slideshow: true,
    sync: "#carouselslider"
  });
});

</script>