<link href="<?=MEDIA_URL ?>css/flexslider.css" rel="stylesheet">

<div id="content" class="paddin30"> 
        	<div id="content-top">
            
                            <div class="top-left">MOTO EXPERT <br /><span>MOTOS D'OCCASION</span></div>
        	</div>
       	  <div id="navi-fiche">
          	  <a href="#" class="previus">RETOUR A LA LISTE D'ANNONCES </a>

            
            <div class="align-right text-right">
            	<a href="#" class="previus border-right">PRECEDENTE</a><a href="" class="suivante">SUIVANTE</a>
            </div>

          </div>
          <!-- //*** DETAILS  //-->
          <div id="details">
          	<div class="col2 align-left">
            	<div class="gallery">
                   <DIV class="flexslider" id="imageitems">
                        <UL class="slides">
                          <?php
                          $config = Zend_Registry::get('config');
                          foreach ($this->photoAnnonces as $photo1) :
                            $foto = str_replace(",",".",$photo1['nom_fichier']);    
                            $ruta = $config->app->photoUrl. $this->detailAnnonces['departement'].'/'.$foto;
                          ?>
                          <LI><IMG   alt="" src="<?=$ruta;?>"></LI>
                          <?php endforeach; ?>
                        </UL>
                      </DIV>
                   
                  
                      <DIV class="flexslider" id="carouselslider">
                        <UL class="slides">
                          <?php
                          $config = Zend_Registry::get('config');
                          foreach ($this->photoAnnonces as $photo2) :
                            $foto = str_replace(",",".",$photo2['nom_fichier']);    
                            $ruta = $config->app->photoUrl. $this->detailAnnonces['departement'].'/'.$foto;
                          ?>
                          <LI><IMG alt="" src="<?=$ruta;?>"></LI>
                           <?php endforeach; ?>
                        </UL>
                   
            </DIV>
                </div>
                
               </div>
               
   
          	<div class="col2 align-right">
            	<div class="partager"><a href="http://www.facebook.com" target="_blank">
                    <img src="<?=MEDIA_URL ?>images/p-facebook.jpg" width="26" height="26" /></a>
                    <a href="http://www.twitter.com" target="_blank">
                        <img src="<?=MEDIA_URL ?>images/p-twitter.jpg" width="26" height="26" />
                    </a>Partager
                </div>
                    
                <h2><?=$this->detailAnnonces['titre'];?></h2>
                <div class="price"><?=$this->detailAnnonces['prix'];?> €</div>
                <div class="col2  align-left">
                <?php
                if($this->detailAnnonces['controle']==1):
                ?>
                <a href="#" class="visuel visu-gara">CONTRÛLE VISUEL</a> 
                <?php endif;
                if($this->detailAnnonces['garantie']==1):
                ?>
                <a href="#" class="garantie visu-gara">GARANTIE </a>
                <?php endif;?>
                </div>
                 <div class="col2  align-left">
                 	<p>Annonce 4902113260000</p>
                    <p>Publiée le <?php echo date('d/m/Y', $this->detailAnnonces['date']);?></p>
                    <p><br/></p>
                    <p><strong>Marque</strong> : <?=$this->detailAnnonces['marque'];?></p>
                    <p><strong>Modèle </strong>: <?=$this->detailAnnonces['modele'];?></p>
                    <p><strong>Catégorie</strong> : <?=$this->detailAnnonces['nom_cat'];?></p>
                    <p><strong>Couleur</strong> : <?=$this->detailAnnonces['couleur'];?></p>
                    <p><strong>Cylindrée</strong> : <?=$this->detailAnnonces['cylindree'];?> cm3</p>
                    <p><strong>Km</strong> : <?=$this->detailAnnonces['km'];?></p>
                    <p><strong>Année</strong> : <?=$this->detailAnnonces['annee'];?></p>
                    <?php if($this->detailAnnonces['nom']!=""): ?>
                    <p><strong>Magasin </strong>: <?=$this->detailAnnonces['nom'];?></p>
                    <?php endif;?>
                    <p><strong>Département</strong> : <?=$this->detailAnnonces['departement'];?></p>
                    <hr />
                    <p><strong>Descriptif</strong> :</p>
                   <p>
                      <?=$this->detailAnnonces['descr_site'];?> 
                   </p>
                    <p></p>
 
              </div>
              </div>
               
               <div style="width:100%; height:10px; clear:both"></div>
               <?php if($this->detailAnnonces['type_occaz']==1): ?>
               <div class="col2 align-left"> 
                <div class="subtitle">
                    <div class="icontitle icon-contact">
                        CONTACTEZ DIRECTEMENT LE VENDEUR
                    </div>
                </div>
              
              <div class="col2 align-left margin-top">
                    <p><?php echo $this->detailAnnonces['nom'];?></p>
                    <p>Port: <?=$this->detailAnnonces['tel'];?> </p>
              </div>
            </div>
            <?php endif;?>
            <!-- SI ES TIENDA -->   
            <?php if($this->detailAnnonces['type_occaz']==2): ?>
            <div class="col2 align-left"> 
                <div class="subtitle">
                    <div class="icontitle icon-contact">
                         CONTACTEZ DIRECTEMENT LE MAGASIN
                    </div>
                </div>
              <div class="top-left">MOTO EXPERT <br /><span>METZ </span></div>
              <div class="col2 align-left margin-top">
              	<div class="col21"><img src="<?=MEDIA_URL ?>images/map.jpg" width="222" height="119" /></div>
                <div class="col22">
                	<div class="subtitle2">
                		PLAN INTERACTIF 
              		</div>
                    <p><?=$this->detailAnnonces['adresse'];?></p>
                	<p>Tél. : <?=$this->detailAnnonces['tel'];?></p>
                    <p>Fax : <?=$this->detailAnnonces['fax'];?> </p>
                    <h3>HORAIRES D'OUVERTURE</h3>
                    <p><?=$this->detailAnnonces['horaires'];?></p>
                </div>
              
              </div>
            </div>
            <?php endif;?>   
               
              
              <div class="col2  align-right">
              <div class="col2  align-left">
                 <div class="subtitle">
                	<div class="icontitle icon-envoyer">ENVOYER UN MAIL</div>
                 </div>
              <form id="form1" name="form1" method="post" action="">
              
              
                  	<label for="textfield">Nom* :</label>
                    <input type="text" name="textfield" id="textfield" />
                 
                 
                 	<label for="textfield2">Prénom* :</label>
                    <input type="text" name="textfield2" id="textfield2" />
                <label for="textfield3">Adresse :</label>
                    <input type="text" name="textfield3" id="textfield3" />
                    <label for="textfield4">Code postal* :</label>
                    <input type="text" name="textfield4" class="inputcol2" id="textfield4" />
                    
                    <label for="textfield5">Ville :</label>
                    <input type="text" name="textfield5" class="inputcol2" id="textfield5" />
                    <label for="textfield6">Téléphone : </label>
                    <input type="text" name="textfield6" id="textfield6" />
                    <label for="textfield7">E-mail :*</label>
                    <input type="text" name="textfield7" id="textfield7" />
                    
                    <label for="textarea">Message : </label>
                <textarea name="textarea" id="textarea" cols="45" rows="5"></textarea>
                    <div class="fomrinfo">
                    	<span>Veuillez saisir les lettres de limage dans le champ situé sous l'image en respectant les majuscules et les minuscules.</span>
                    <div class="captcha"><img src="<?=MEDIA_URL ?>images/captcha.jpg" width="126" height="86" /></div>
                   <div class="condition">
                   	<input name="" type="checkbox" value="" />En cochant cette case, je souhaite recevoir la newsletter Moto Expert
                   
                   </div>
                    
                    <input name="ENVOYER" type="submit" id="ENVOYER" value="ENVOYER" />
                    
                    </div>

              </form>
              </div>  
                 
                
                
            </div>
          </div>
          
          
          
          
          
          <div id="navi-fiche">
          	  <a href="#" class="previus">RETOUR A LA LISTE D'ANNONCES </a>

           
            <div class="align-right">
            	<a href="#" class="previus border-right">PRECEDENTE</a><a href="" class="suivante">SUIVANTE</a>
            </div>

          </div>
          </div>
          

<script src="<?php echo MEDIA_URL ?>js/jquery.flexslider-min.js" type="text/javascript"></script>          

<script type="text/javascript">
jQuery(window).load(function() {

  jQuery('#carouselslider').flexslider({
    animation: "slide",
    controlNav: false,
    animationLoop: true,
    slideshow: true,
    itemWidth: 110,
    itemMargin:0,
    asNavFor: '#imageitems'
  });
   
  jQuery('#imageitems').flexslider({
    animation: "fade",
	directionNav: false,
    controlNav: false,
    animationLoop: true,
    slideshow: true,
    sync: "#carouselslider"
  });
});

</script>