<div id="content-p28">
	<div id="content-top">

		<div class="top-left">
			<span>VOTRE ANNONCE MOTO</span>
		</div>
	</div>

	<!-- //*** DETAILS  //-->
	<div class="caract-content">
		<form name="form1" method="post" action="">
			<div class="title-content">CARACTERISTIQUES</div>
			<div class="caract-wapper">
				<div class="caract-286">
					<div class="result-desc">
						<div class="result-date">05/02114</div>
						<p>
							<strong>Suzuki RMZ 250</strong><br /> Roadster - Honda - CB 600 F
							ABS -<br> 600 cm3 - 15550 km - Année 2005
						</p>
						<div class="price">4200 €</div>
					</div>

				</div>
				<div class="caract-408">
					<strong>Descriptif :</strong><br> <br> Entretien à jour sur
					facture.<br> nibh euismod tincidunt ut laoreet dolore magna aliquam
					erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci
					tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo
					consequat. Duis autem vel eum iriure dolor in
				</div>
			</div>
			<div class="caract-subtitle">MODIFIER</div>

			<div class="title-content">AJOUTER DES PHOTOS</div>
			<div class="caract-wapper">
				<div class="caract-286">
					<div class="upload-g">
						<input type="file" name="upload" />
					</div>
					<div class="upload-m">
						<input type="file" name="upload" />
					</div>
					<div class="upload-m">
						<input type="file" name="upload" />
					</div>
					<div class="upload-m">
						<input type="file" name="upload" />
					</div>
					<div class="upload-m">
						<input type="file" name="upload" />
					</div>

				</div>
				<div class="caract-408">
					<strong>Augmentez la visibilité de votre annonce en ajoutant une ou
						plusieurs photos.</strong><br> <br>
					<p class="p11">
						- Mettez une photo de votre moto UNIQUEMENT de 3 quart comme photo
						principale.<br> - Utilisez les photos annexes pour présenter les
						autres vues de votre moto.<br> - Ne faites pas apparaître votre
						plaque d’immatriculation pour éviter toutes fraudes.<br>
						Motoexpert.fr se réserve le droit de supprimer toutes annonces ou
						photos qui ne correspondraient pas.
					</p>
				</div>
			</div>
			<div class="title-content">
				AFFICHAGE DE VOS<br /> COORDONNÉES SUR LE SITE
			</div>

			<div class="caract-wapper">
				<p class="p11">
					<strong>(Choisissez au minimun 1 moyen de contact).</strong>
				</p>
				<p class="pm16">
					Autoriser les internautes à vous contacter par e-mail : <br>
				</p>
				<p class="p11">(votre adresse n’apparaît pas en clair sur le site)</p>
				<p class="pinput">
					<input type="radio" name="radio" id="radio" value="radio"> <label
						for="radio">Oui</label> <input type="radio" name="radio"
						id="radio" value="radio"> <label for="radio">Nom</label>
				</p>




				<p class="pm16">
					Faire figurer votre numéro de téléphone fixe sur votre annonce :<br>
				</p>

				<p class="pinput">
					<input type="radio" name="radio" id="radio" value="radio"> <label
						for="radio">Oui</label> <input type="radio" name="radio"
						id="radio" value="radio"> <label for="radio">Nom</label>
				</p>


				<p class="pm16">
					Faire figurer votre numéro de portable sur votre annonce : <br>
				</p>
				<p class="pinput">
					<input type="radio" name="radio" id="radio" value="radio"> <label
						for="radio">Oui</label> <input type="radio" name="radio"
						id="radio" value="radio"> <label for="radio">Nom</label>
				</p>


				<p class="pm16">
					<input name="" type="checkbox" value=""> permettre a Moto Expert de
					diffuser cette annonce a ses partenaires <br>
				</p>


			</div>

			<div class="title-content"></div>
			<a href="#" class="btn-ye">PUBLIER VOTRE ANNONCE</a>
		</form>

	
		<div id="movil">

			<div class="title-content">CARACTERISTIQUES</div>
			<form name="frmcarcth" method="post" action="">
			<div class="caract-wapper">
				<p>
					<?= $this->form->category?>
				</p>
				<p>
					<?= $this->form->marque?>
				</p>
				<p>
					<?= $this->form->modele?>
				</p>
				<p>
					<input name="annee" type="text" placeholder="Année">
				</p>
				<p>
					<input name="cylindree" type="text" placeholder="Cylindrée">
				</p>
				<p>
					<input name="couleur" type="text" placeholder="Couleur">
				</p>
				<p>
					<input name="km" type="text" placeholder="Kilométrage">
				</p>
				<p>
					<input name="" type="checkbox" value="">Pas de compteur
					kilométrique
				</p>
				<p>
					<input name="prix" type="text" placeholder="Prix">
				</p>
				<p>
					<input name="" type="checkbox" value="">ou à débattre
				</p>
				<p>
					<input name="descr_site" type="text" placeholder="Descriptif">
				</p>
				<p>
					<input type="submit" name="button2" id="button2"
						value="ENREGISTRER" />
				</p>


			</div>
			</form>
			<div class="caract-wapper">

				<div class="login  align-left ">
					<div class="login-content">
						<h3>VOTRE ANNONCEA ÉTÉ ENREGISTRÉE</h3>
						<p>
							Elle sera publiée après validation<br> des équipe Moto Expert
						</p>
					</div>

					<input name="ENVOYER" type="submit" id="ENVOYER" value="FERMER" />


				</div>


				<div class="login  align-left ">

					<p class="login-tab color-orange">SUPPRIMER LA PHOTO</p>
					<p class="login-tab">DEPUIS LA BIBLIOTHEQUE</p>
					<p class="login-tab no-boerder">PRENDRE UNE PHOTO</p>
					<input name="ENVOYER" type="submit" class="no-margin" id="ENVOYER"
						value="ANNULER" />
				</div>
				<br />
				<br />


			</div>

		</div>
		<!---// end movil //-->

	</div>





	<div id="navi-fiche">
		<div class="align-right"></div>

	</div>
</div>

<script	src="<?php echo MEDIA_URL ?>js/marque-back.js"></script>
