<script type='text/javascript'>
jQuery.noConflict();
    jQuery(function(){
        //Maps your button click event to the File Upload click event
        jQuery("#img-preview").click(function () {
             jQuery("#file1").trigger('click');
        });
		        //Maps your button click event to the File Upload click event
        jQuery("#img-preview2").click(function () {
             jQuery("#file2").trigger('click');
        });
		        //Maps your button click event to the File Upload click event
        jQuery("#img-preview3").click(function () {
             jQuery("#file3").trigger('click');
        });
		        //Maps your button click event to the File Upload click event
        jQuery("#img-preview4").click(function () {
             jQuery("#file4").trigger('click');
        });
		        //Maps your button click event to the File Upload click event
        jQuery("#img-preview5").click(function () {
             jQuery("#file5").trigger('click');
        });
    });
	
</script>
<div id="content-p28">
	<div id="content-top">

		<div class="top-left">
			<span>VOTRE ANNONCE MOTO</span>
		</div>
	</div>

	<!-- //*** DETAILS  //-->
	<div class="caract-content">
		<form name="form1" method="post" action="/compte/annonce-complete" enctype="multipart/form-data">
		<?php if ($this->valid) {?>
		
			<div class="title-content">CARACTERISTIQUES</div>
			<div class="caract-wapper">
				<div class="caract-286">
					<div class="result-desc">
						<div class="result-date">
                                                <?php
                                                 $d = new App_Date_Calc();
                                                    echo  $d->daysToDate($this->caract['date_crea'], "%d/%m/%y");
                                                ?>
                                                </div>
						<p>
							<strong><?= $this->caract['marque'] ?> <?= $this->caract['modele'] ?> 250</strong><br /> <?= $this->caract['id_cat'] ?> - <?= $this->caract['marque'] ?> 
							<!-- ABS--> -<br> <?= $this->caract['cylindree'] ?> cm3 - <?= $this->caract['km'] ?> km - Année <?= $this->caract['annee'] ?>
						</p>
						<div class="price"><?= $this->caract['prix'] ?> €</div>
					</div>

				</div>
				<div class="caract-408">
					<strong>Descriptif :</strong><br> 
					<?= $this->caract['descr_site'] ?>
				</div>
			</div>
			<a href="#" onClick="dispatchpopup();" class="btn-submit">MODIFIER</a>
			
			<?php } ?>

			<output id="imgim"></output>

			<div class="title-content">AJOUTER DES PHOTOS</div>
			<div class="caract-wapper">
				<div class="caract-286">

				<input type="hidden" name="cod_id" value="<?= $this->idannunce ?>"/>
				<input type="hidden" name="ref" value="<?= $this->caract["ref"] ?>" />
					<div class="upload-g">
                    	 <div id="img-delete-1"></div>
						<div id="img-preview">
										
                            <?php if(isset($this->photos[1])) {
                            
                            ?>
                            <img src="<?= PHOTO_URL.$this->urlPhoto . $this->photos[1]['nom_fichier'] ?>" width="137" height="102" />
                            <input type="hidden" name="foto1" value="<?= $this->photos[1]['id_photo'] ?>"/>
                            <?php } else {?>
                            <img src="<?=MEDIA_URL ?>images/file-g.jpg" width="137" height="102" />
                            <?php } ?>

						</div>
						<?= $this->form->file1 ?>
					</div>
                    <script>
                    function deleteimage2(){						
						 jQuery("#img-preview2").html('<img src="<?=MEDIA_URL ?>images/file-m.jpg" width="67" height="48" />');
						 jQuery("#img-delete-2").html('');
						}
					function deleteimage3(){						
						 jQuery("#img-preview3").html('<img src="<?=MEDIA_URL ?>images/file-m.jpg" width="67" height="48" />');
						 jQuery("#img-delete-3").html('');
						}
					function deleteimage4(){						
						 jQuery("#img-preview4").html('<img src="<?=MEDIA_URL ?>images/file-m.jpg" width="67" height="48" />');
						 jQuery("#img-delete-4").html('');
						}
					function deleteimage5(){						
						 jQuery("#img-preview5").html('<img src="<?=MEDIA_URL ?>images/file-m.jpg" width="67" height="48" />');
						 jQuery("#img-delete-5").html('');
						}
                    </script>
					<div class="upload-m">
                    	 <div id="img-delete-2"><?php if(isset($this->photos[2])) { echo '<div class="delete-upload-g"><a href="javascript:deleteimage2();"  onclick="return confirm(\'Etes-vous sûr de vouloir supprimer la photo ?\')"><img src="'.MEDIA_URL.'images/close.png" width="20" height="20"></a></div>'; }?></div>
						<div id="img-preview2">
<?php if(isset($this->photos[2])) {?>
<img src="<?= PHOTO_URL. $this->urlPhoto.$this->photos[2]['nom_fichier'] ?>" width="67" height="48" />
<input type="hidden" name="foto2" value="<?= $this->photos[2]['id_photo'] ?>"/>
<?php } else {?>
<img src="<?=MEDIA_URL ?>images/file-m.jpg" width="67" height="48" />
<?php } ?>	
							
						</div>
						<?= $this->form->file2 ?>
					</div>
					<div class="upload-m">
                     <div id="img-delete-3"><?php if(isset($this->photos[3])) { echo '<div class="delete-upload-g"><a href="javascript:deleteimage3();""  onclick="return confirm(\'Etes-vous sûr de vouloir supprimer la photo ?\')"><img src="'.MEDIA_URL.'images/close.png" width="20" height="20"></a></div>'; }?></div>
						<div id="img-preview3">
<?php if(isset($this->photos[3])) {?>
<img src="<?= PHOTO_URL.$this->urlPhoto.$this->photos[3]['nom_fichier'] ?>" width="67" height="48" />
<input type="hidden" name="foto3" value="<?= $this->photos[3]['id_photo'] ?>"/>
<?php } else {?>
<img src="<?=MEDIA_URL ?>images/file-m.jpg" width="67" height="48" />
<?php } ?>						</div>
						<?= $this->form->file3 ?>
					</div>
					<div class="upload-m">
                     <div id="img-delete-4"><?php if(isset($this->photos[4])) { echo '<div class="delete-upload-g"><a href="javascript:deleteimage4();"  onclick="return confirm(\'Etes-vous sûr de vouloir supprimer la photo ?\')"><img src="'.MEDIA_URL.'images/close.png" width="20" height="20"></a></div>'; }?></div>
						<div id="img-preview4">
<?php if(isset($this->photos[4])) {?>
<img src="<?= PHOTO_URL.$this->urlPhoto.$this->photos[4]['nom_fichier'] ?>" width="67" height="48" />
<input type="hidden" name="foto4" value="<?= $this->photos[4]['id_photo'] ?>"/>
<?php } else {?>
<img src="<?=MEDIA_URL ?>images/file-m.jpg" width="67" height="48" />
<?php } ?>									
						</div>
						<?= $this->form->file4 ?>
					</div>
					<div class="upload-m">
                     <div id="img-delete-5"><?php if(isset($this->photos[5])) { echo '<div class="delete-upload-g"><a href="javascript:deleteimage5();"  onclick="return confirm(\'Etes-vous sûr de vouloir supprimer la photo ?\')"><img src="'.MEDIA_URL.'images/close.png" width="20" height="20"></a></div>'; }?></div>
						<div id="img-preview5">
<?php if(isset($this->photos[5])) {?>
<img src="<?=  PHOTO_URL.$this->urlPhoto . $this->photos[5]['nom_fichier'] ?>" width="67" height="48" />
<input type="hidden" name="foto5" value="<?= $this->photos[5]['id_photo'] ?>"/>
<?php } else {?>
<img src="<?=MEDIA_URL ?>images/file-m.jpg" width="67" height="48" />
<?php } ?>		
						</div>
						<?= $this->form->file5 ?>
					</div>

				</div>
				<div class="caract-408">
					<strong>Augmentez la visibilité de votre annonce en ajoutant une ou
						plusieurs photos.</strong><br> <br>
					<p class="p11">
						- Mettez une photo de votre moto UNIQUEMENT de 3 quart comme photo
						principale.<br> - Utilisez les photos annexes pour présenter les
						autres vues de votre moto.<br> - Ne faites pas apparaître votre
						plaque d’immatriculation pour éviter toutes fraudes.<br>
						Motoexpert.fr se réserve le droit de supprimer toutes annonces ou
						photos qui ne correspondraient pas.
					</p>
				</div>
			</div>
			<div class="title-content">
				AFFICHAGE DE VOS<br /> COORDONNÉES SUR LE SITE
			</div>

			<div class="caract-wapper">
			<input type="hidden" name="departement" value="<?php echo $this->params['departement']?>"/>
				<p class="p11">
					<strong>(Choisissez au minimun 1 moyen de contact).</strong>
				</p>
				<p class="pm16">
					Autoriser les internautes à vous contacter par e-mail : <br>
				</p>
				<p class="p11">(votre adresse n’apparaît pas en clair sur le site)				
				</p>
				<p class="pinput">
					<input type="radio" name="rep_mail" id="radio1" value="1" <?php echo ($this->params['rep_mail'] == "1")?'checked="checked"':'' ?>> 
					<label for="radio1">Oui</label> 
					<input type="radio" name="rep_mail" id="radio2" value="0" <?php echo ($this->params['rep_mail'] == "0")?'checked="checked"':'' ?>> 
					<label for="radio2">Non</label>
				</p>




				<p class="pm16">
					Faire figurer votre numéro de téléphone fixe sur votre annonce :<br>
				</p>

				<p class="pinput">
					<input type="radio" name="rep_tel" id="radio3" value="1" <?php echo ($this->params['rep_tel'] == "1")?'checked="checked"':'' ?>> 
					<label for="radio3">Oui</label> 
					<input type="radio" name="rep_tel" id="radio4" value="0" <?php echo ($this->params['rep_tel'] == "0")?'checked="checked"':'' ?>> 
					<label for="radio4">Non</label>
				</p>


				<p class="pm16">
					Faire figurer votre numéro de portable sur votre annonce : <br>
				</p>
				<p class="pinput">
					<input type="radio" name="rep_port" id="radio5" value="1" <?php echo ($this->params['rep_port'] == "1")?'checked="checked"':'' ?>> 
					<label for="radio5">Oui</label> 
					<input type="radio" name="rep_port" id="radio6" value="0" <?php echo ($this->params['rep_port'] == "0")?'checked="checked"':'' ?>> 
					<label for="radio6">Non</label>
				</p>
				<p class="pm16">
					<input name="parution" type="checkbox" <?php echo ($this->params['parution'] == "1")?'checked="checked"':'' ?>> permettre a Moto Expert de
					diffuser cette annonce a ses partenaires <br>
				</p>


			</div>

			<div class="title-content"></div>
			<button type="submit" class="btn-ye" <?php echo (!$this->valid)?'disabled="disabled"':'' ?>>PUBLIER VOTRE ANNONCE</button>
			
		</form>

<!-- 
		<div id="movil">

			<div class="title-content">CARACTERISTIQUES</div>
			<div class="caract-wapper">
				<p>
					<select name="select2" id="select2">
						<option value="0">Catégorie</option>
					</select>
				</p>
				<p>
					<select name="select2" id="select2">
						<option value="0">Marque</option>
					</select>
				</p>
				<p>
					<select name="select2" id="select2">
						<option value="0">Modèle</option>
					</select>
				</p>
				<p>
					<input name="" type="text" placeholder="Année">
				</p>
				<p>
					<input name="" type="text" placeholder="Cylindrée">
				</p>
				<p>
					<input name="" type="text" placeholder="Couleur">
				</p>
				<p>
					<input name="" type="text" placeholder="Kilométrage">
				</p>
				<p>
					<input name="" type="checkbox" value="">Pas de compteur
					kilométrique
				</p>
				<p>
					<input name="" type="text" placeholder="Prix">
				</p>
				<p>
					<input name="" type="checkbox" value="">ou à débattre
				</p>
				<p>
					<input name="" type="text" placeholder="Descriptif">
				</p>
				<p>
					<input type="submit" name="button2" id="button2"
						value="ENREGISTRER" />
				</p>



				<div class="caract-wapper">

					<div class="login  align-left ">
						<div class="login-content">
							<h3>VOTRE ANNONCEA ÉTÉ ENREGISTRÉE</h3>
							<p>
								Elle sera publiée après validation<br> des équipe Moto Expert
							</p>
						</div>

						<input name="ENVOYER" type="submit" id="ENVOYER" value="FERMER" />


					</div>


					<div class="login  align-left ">

						<p class="login-tab color-orange">SUPPRIMER LA PHOTO</p>
						<p class="login-tab">DEPUIS LA BIBLIOTHEQUE</p>
						<p class="login-tab no-boerder">PRENDRE UNE PHOTO</p>
						<input name="ENVOYER" type="submit" class="no-margin" id="ENVOYER"
							value="ANNULER" />
					</div>
					<br /> <br />


				</div>
			</div>
		</div>-->
		<!---// end movil //-->

	</div>





	<div id="navi-fiche">
		<div class="align-right"></div>

	</div>
</div>
 <script>

				 function validateform1(){
				   
				 if (document.getElementById("deparment").value == "0"&&document.getElementById("category").value == "0"&&document.getElementById("marque").value == "0"&&document.getElementById("modele").value == "0"&&document.getElementById("annee").value == ""&&document.getElementById("cylindree").value == ""&&document.getElementById("couleur").value == ""&&document.getElementById("km").value == ""&&document.getElementById("prix").value == ""){ 
					jQuery('#deparment').addClass( 'error' );
					jQuery('#category').addClass( 'error' );
					jQuery('#marque').addClass( 'error' );  
					jQuery('#modele').addClass( 'error' );				   			
				   jQuery('#annee').addClass( 'error' );  				   
				   jQuery('#anneelabel').addClass( 'error' );
				   jQuery('#anneelabel').removeClass( 'nodisplay');
				   jQuery('#cylindree').addClass( 'error' );  				   
				   jQuery('#cylindreelabel').addClass( 'error' );
				   jQuery('#cylindreelabel').removeClass( 'nodisplay');
				   jQuery('#couleur').addClass( 'error' );  				   
				   jQuery('#couleurlabel').addClass( 'error' );
				   jQuery('#couleurlabel').removeClass( 'nodisplay');	
				   jQuery('#km').addClass( 'error' );  				   
				   jQuery('#kmlabel').addClass( 'error' );
				   jQuery('#kmlabel').removeClass( 'nodisplay');
				   jQuery('#prix').addClass( 'error' );  				   
				   jQuery('#prixlabel').addClass( 'error' );
				   jQuery('#prixlabel').removeClass( 'nodisplay');
				   	return false; 
				  }
				
				  if (document.getElementById("deparment").value == "0"){ 
				   jQuery('#deparment').addClass( 'error' );  				   
				   //$('#nomlabel').addClass( 'error' );
				  // $('#nomlabel').removeClass( 'nodisplay');				
					return false; 
				  }
				 if (document.getElementById("category").value == "0"){ 
				   jQuery('#category').addClass( 'error' );  				   
				   //$('#prenomlabel').addClass( 'error' );
				   //$('#prenomlabel').removeClass( 'nodisplay');				
					return false; 
				  }
				  if (document.getElementById("marque").value == "0"){ 
				  jQuery('#marque').addClass( 'error' );  				   
				   //$('#adresselabel').addClass( 'error' );
				   //$('#adresselabel').removeClass( 'nodisplay');				
					return false; 
				  } 
				  if (document.getElementById("modele").value == "0"){ 
				   jQuery('#modele').addClass( 'error' );  				   
				  // $('#code_postallabel').addClass( 'error' );
				  // $('#code_postallabel').removeClass( 'nodisplay');				
					return false; 
				  }
				  if (document.getElementById("annee").value == ""){ 
				   jQuery('#annee').addClass( 'error' );  				   
				   jQuery('#anneelabel').addClass( 'error' );
				   jQuery('#anneelabel').removeClass( 'nodisplay');				
					return false; 
				  } 
				   if (document.getElementById("cylindree").value == ""){ 
				   jQuery('#cylindree').addClass( 'error' );  				   
				   jQuery('#cylindreelabel').addClass( 'error' );
				   jQuery('#cylindreelabel').removeClass( 'nodisplay');				
					return false; 
				  }
				   if (document.getElementById("couleur").value == ""){ 
				   jQuery('#couleur').addClass( 'error' );  				   
				   jQuery('#couleurlabel').addClass( 'error' );
				   jQuery('#couleurlabel').removeClass( 'nodisplay');				
					return false; 
				  }				  
				  if (document.getElementById("km").value == ""){ 
				   jQuery('#km').addClass( 'error' );  				   
				   jQuery('#kmlabel').addClass( 'error' );
				   jQuery('#kmlabel').removeClass( 'nodisplay');				
					return false; 
				  } 
        		if (document.getElementById("prix").value == ""){ 
				   jQuery('#prix').addClass( 'error' );  				   
				   jQuery('#prixlabel').addClass( 'error' );
				   jQuery('#prixlabel').removeClass( 'nodisplay');				
					return false; 
				  } 
				return true;
				}
              /*************************************************/
				 function removevalidateform1(){

				 if (document.getElementById("deparment").value != "0"){ 
				   jQuery('#deparment').removeClass( 'error' );  	
				  }
				   if (document.getElementById("category").value != "0"){ 
				   jQuery('#category').removeClass( 'error' );  				   
				  }
				  if (document.getElementById("marque").value != "0"){ 
				  jQuery('#marque').removeClass( 'error' );  				   

				  } 
				  if (document.getElementById("modele").value != "0"){ 
				   jQuery('#modele').removeClass( 'error' );  				   

				  }
				  if (document.getElementById("annee").value != ""){ 
				   jQuery('#annee').removeClass( 'error' );  				   
				   jQuery('#anneelabel').removeClass( 'error' );
				   jQuery('#anneelabel').addClass( 'nodisplay');				
					return false; 
				  } 
				   if (document.getElementById("cylindree").value != ""){ 
				   jQuery('#cylindree').removeClass( 'error' );  				   
				   jQuery('#cylindreelabel').removeClass( 'error' );
				   jQuery('#cylindreelabel').addClass( 'nodisplay');				
					return false; 
				  }
				   if (document.getElementById("couleur").value != ""){ 
				   jQuery('#couleur').removeClass( 'error' );  				   
				   jQuery('#couleurlabel').removeClass( 'error' );
				   jQuery('#couleurlabel').addClass( 'nodisplay');				
					return false; 
				  }				  
				  if (document.getElementById("km").value != ""){ 
				   jQuery('#km').removeClass( 'error' );  				   
				   jQuery('#kmlabel').removeClass( 'error' );
				   jQuery('#kmlabel').addClass( 'nodisplay');				
					return false; 
				  } 
        		if (document.getElementById("prix").value != ""){ 
				   jQuery('#prix').removeClass( 'error' );  				   
				   jQuery('#prixlabel').removeClass( 'error' );
				   jQuery('#prixlabel').addClass( 'nodisplay');				
					return false; 
				  } 
				  				   
				  
				} 
        </script>  


<div id="my_lightbox">
	<div id="wrapper-form">
		<div id="new-form">
			<div id="form-navigation">
				<a href="#" class="new-prev" onClick="jQuery('#my_lightbox').trigger('close');">RETOUR</a><p>VOTRE VEHICULE</p>
			</div>

			<form name="form1" id="form1" method="post" action="?register=valid"  onSubmit="return validateform1()">
			<?= $this->form->id?>
			<p>
					<?= $this->form->deparment?>
			</p>				
			<p>
					<?= $this->form->category?>
			</p>
				<p>
					<?= $this->form->marque?>
				</p>
				<p>
					<?= $this->form->modele?>
				</p>
				<p>					
					<?= $this->form->annee?>
                     <label for="annee" id="anneelabel"  class="nodisplay">Veuillez renseigner votre code annee</label>
				</p>
				<p>
					<?= $this->form->cylindree?>
                     <label for="cylindree" id="cylindreelabel"  class="nodisplay">Veuillez renseigner votre code cylindree</label>
				</p>
				<p>					
					<?= $this->form->couleur?>
                    <label for="couleur" id="couleurlabel"  class="nodisplay">Veuillez renseigner votre code couleur</label>
				</p>
				<p>					
					<?= $this->form->km?>
				</p>

				<p>					
					<?= $this->form->prix?>
                    <label for="km" id="kmlabel"  class="nodisplay">Veuillez renseigner votre code km</label>
				</p>

				<p>
					<?= $this->form->descr_site?>
				</p>
                <p class="validatecheckox"><input name="" type="checkbox" class="validcheckox" value="">Pas de compteur kilométrique
				</p>
                <p class="validatecheckox"><input name="" type="checkbox"  class="validcheckox" value="">ou à débattre
				</p>               
                
                
                
                <p>
                <a onClick="jQuery('#my_lightbox').trigger('close');" class="btn-100">ANNULER</a>
                </p>
				<p>
					<input type="submit" name="button2" id="button2"
						value="ENREGISTRER" />
				</p>
			</form>
		</div>


	</div>
</div>

<!-- guardar anuncio-->

<div id="my_lightbox_confirm2" style="display: none;">
	<div id="wrapper-form">
		<div id="new-form">
			<div id="form-navigation">
			</div>
				<div class="caract-wappers">
					<div class="login  align-left ">
						<div class="login-content">
							<h3>VOTRE ANNONCEA ÉTÉ ENREGISTRÉE</h3>
							<p>
								Elle sera publiée après validation<br> des équipe Moto Expert
							</p>
						</div>
						<input name="ENVOYER" type="submit" id="ENVOYER" value="FERMER" />
					</div>
					<div class="login  align-left ">
						<p class="login-tab color-orange">SUPPRIMER LA PHOTO</p>
						<p class="login-tab">DEPUIS LA BIBLIOTHEQUE</p>
						<p class="login-tab no-boerder">PRENDRE UNE PHOTO</p>
						<input name="ENVOYER" type="submit" class="no-margin" id="ENVOYER"
							value="ANNULER" />
					</div>
				</div>
		</div>
	</div>
</div>
<!--  fin -->



<script	src="<?php echo MEDIA_URL ?>js/marque-back2.js"></script>


<script>
jQuery(function(){
    
    var combodep = {        
        init : function() {
           this.Combo("#marque", "#modele", "--- MARQUE ---", "/default/index/get-modele", "id", "value");           
        },        
        Combo : function (c, cd, def, url, fieldv, fields) {           
            
                var actual = jQuery(c);
                
                if (actual.val() != 0) {
                                        
                    
                	jQuery(cd).removeAttr("disabled");
                	jQuery.ajax({
                        url: url,
                        type: 'post',
                        data: {
                           id : actual.val()
                        },
                        dataType: 'json',                        
                        success: function(data){
                        	jQuery(cd).html("<option value='0'> -- Modele -- </option>");

                        	jQuery.each(data, function(index, value){
                                	var selec = ' ';
                                	console.log(value[fieldv] + " " + "<?php echo @$this->params['modele']?>");
                                	if (value[fieldv] == "<?php echo @$this->params['modele']?>")
                                         var selec = 'selected="selected "';
                                	jQuery(cd).append("<option "+ selec +" value='"+value[fieldv]+"_"+value[fields]+"'>"+value[fields]+"</option>");
                                });

                                
                        }
                    });                    
                } else {
                	jQuery(cd).html("");
                	jQuery(cd).append("<option value='0'> -- Modele -- </option>");
                	jQuery(cd).attr("disabled", "disabled");
                    
                    
                }
            
       }
    };    
    combodep.init();
    
});



</script>

	
<script>
  var dispatchpopup = function(){  
    jQuery('#my_lightbox').lightbox_me({
      centered: true,
      onLoad: function() {
        jQuery('#my_lightbox_text').html("Stuff");
      }
    });
  }
</script>

<script>
  var confirm2 = function(){  
    jQuery('#my_lightbox_confirm2').lightbox_me({
      centered: true,
      onLoad: function() {
        jQuery('#my_lightbox_confirm2').html("Stuff");
      }
    });
  }
</script>


<script>
    if (window.FileReader) {
      function selectfile(evt) {
        var files = evt.target.files;
        var f = files[0];
        var vfile = new FileReader();
      
          vfile.onload = (function(thefile) {
            return function(e) {
              document.getElementById('img-preview').innerHTML = '<img  src="'+ e.target.result +'"   class="image-previ-g"/>';
			  //document.getElementById('img-delete-1').innerHTML = '<div class="delete-upload-g"><a href="#"><img src="<?= MEDIA_URL?>images/close.png" width="20" height="20"></a></div>';

            };
          })(f);
    
          vfile.readAsDataURL(f);
      }
     } else {
      document.getElementById('img-preview').innerHTML = "No preview";
    }
	/******************************************************************************/
    if (window.FileReader) {
      function selectfile2(evt) {
        var files = evt.target.files;
        var f = files[0];
        var vfile = new FileReader();
      
          vfile.onload = (function(thefile) {
            return function(e) {
              document.getElementById('img-preview2').innerHTML = '<img  src="'+ e.target.result +'"  class="image-previ-c"/>';
			  document.getElementById('img-delete-2').innerHTML = '<div class="delete-upload-g"><a href="javascript:deleteimage2()"  onclick="return confirm(\'Etes-vous sûr de vouloir supprimer la photo ?\')"><img src="<?= MEDIA_URL?>images/close.png" width="20" height="20"></a></div>';
            };
          })(f);
    
          vfile.readAsDataURL(f);
      }
     } else {
      document.getElementById('img-preview2').innerHTML = "No preview";
    }
		/******************************************************************************/
    if (window.FileReader) {
      function selectfile3(evt) {
        var files = evt.target.files;
        var f = files[0];
        var vfile = new FileReader();
      
          vfile.onload = (function(thefile) {
            return function(e) {
              document.getElementById('img-preview3').innerHTML = '<img  src="'+ e.target.result +'"  class="image-previ-c" />';
			  document.getElementById('img-delete-3').innerHTML = '<div class="delete-upload-g"><a href="javascript:deleteimage3();"  onclick="return confirm(\'Etes-vous sûr de vouloir supprimer la photo ?\')"><img src="<?= MEDIA_URL?>images/close.png" width="20" height="20"></a></div>';
            };
          })(f);
    
          vfile.readAsDataURL(f);
      }
     } else {
      document.getElementById('img-preview3').innerHTML = "No preview";
    }
		/******************************************************************************/
    if (window.FileReader) {
      function selectfile4(evt) {
        var files = evt.target.files;
        var f = files[0];
        var vfile = new FileReader();
      
          vfile.onload = (function(thefile) {
            return function(e) {
              document.getElementById('img-preview4').innerHTML = '<img  src="'+ e.target.result +'"  class="image-previ-c" />';
			  document.getElementById('img-delete-4').innerHTML = '<div class="delete-upload-g"><a href="javascript:deleteimage4();"  onclick="return confirm(\'Etes-vous sûr de vouloir supprimer la photo ?\')"><img src="<?= MEDIA_URL?>images/close.png" width="20" height="20"></a></div>';
            };
          })(f);
    
          vfile.readAsDataURL(f);
      }
     } else {
      document.getElementById('img-preview4').innerHTML = "No preview";
    }
	
		/******************************************************************************/
    if (window.FileReader) {
      function selectfile5(evt) {
        var files = evt.target.files;
        var f = files[0];
        var vfile = new FileReader();
      
          vfile.onload = (function(thefile) {
            return function(e) {
              document.getElementById('img-preview5').innerHTML = '<img  src="'+ e.target.result +'"   class="image-previ-c" />';
			  document.getElementById('img-delete-5').innerHTML = '<div class="delete-upload-g"><a href="javascript:deleteimage5();" onclick="return confirm(\'Etes-vous sûr de vouloir supprimer la photo ?\')"><img src="<?= MEDIA_URL?>images/close.png" width="20" height="20"></a></div>';
            };
          })(f);
    
          vfile.readAsDataURL(f);
      }
     } else {
      document.getElementById('img-preview5').innerHTML = "No preview";
    }
      document.getElementById('file1').addEventListener('change', selectfile, false);
	  document.getElementById('file2').addEventListener('change', selectfile2, false);
	  document.getElementById('file3').addEventListener('change', selectfile3, false);
	  document.getElementById('file4').addEventListener('change', selectfile4, false);
	  document.getElementById('file5').addEventListener('change', selectfile5, false);
      
    </script>
