<link href="<?=MEDIA_URL ?>css/owl.carousel.css" rel="stylesheet">
<link href="<?=MEDIA_URL ?>css/owl.theme.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700' rel='stylesheet' type='text/css'>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&language=fr-FR"></script>
    <script>
      function initialize() {
        var map_canvas = document.getElementById('map_canvas');
        var map_options = {
          center: new google.maps.LatLng(<?= $this->magasinInfo['latitude'];?>, <?= $this->magasinInfo['longitude'];?>),
          zoom: 13,
		  			//navigationControl: false,
			//draggable: false,
			scrollwheel: true,
			streetViewControl:false,
			mapTypeControl: false,
			zoomControl: false,
			scaleControl: false,		  
		  			zoomControlOptions: {
				style: google.maps.ZoomControlStyle.SMALL
			},
          mapTypeId: google.maps.MapTypeId.ROADMAP,

        }
        var map = new google.maps.Map(map_canvas, map_options);
				var marker = new google.maps.Marker({
    map: map,
    position: map.getCenter()
  });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
<body>
        <div id="content" class="paddin30"> 
        	<div id="content-top">
            
                            <div class="top-left">MOTO EXPERT <br /><span><?= $this->magasinInfo['ville'];?></span></div>
        	</div>
       	  
          <!-- //*** Magasines  //-->
          <div id="details">
                  <div id="slidersh">
                    <div id="owl-demo" class="owl-carousel">
                        
                        <?php
                          $nombreTienda =  strtolower($this->magasinInfo['ville']).'_'.$this->magasinInfo['id_me'];
                          $config = Zend_Registry::get('config');
                          foreach ($this->magasinPhoto as $photo) :
                            $ruta = $config->app->photoUrlTienda.$nombreTienda.'/gallery/gd/'.$photo['nom_fichier'].'.jpg';
                          ?>
                          <div class="item"><img src="<?=$ruta;?>" alt=""></div>
                          <?php endforeach; ?> 
                        <!--<div class="item"><img src="<?=MEDIA_URL ?>images/sliderh/1.jpg" alt=""></div>
                        <div class="item"><img src="<?=MEDIA_URL ?>images/sliderh/2.jpg" alt=""></div>
                        <div class="item"><img src="<?=MEDIA_URL ?>images/sliderh/3.jpg" alt=""></div>
                        <div class="item"><img src="<?=MEDIA_URL ?>images/sliderh/4.jpg" alt=""></div>
                        <div class="item"><img src="<?=MEDIA_URL ?>images/sliderh/1.jpg" alt=""></div>
                        <div class="item"><img src="<?=MEDIA_URL ?>images/sliderh/2.jpg" alt=""></div>
                        <div class="item"><img src="<?=MEDIA_URL ?>images/sliderh/3.jpg" alt=""></div>
                        <div class="item"><img src="<?=MEDIA_URL ?>images/sliderh/4.jpg" alt=""></div>-->
                      </div>
                  
                  
                  </div>
    <script src="<?=MEDIA_URL ?>js/sliderh/jquery-1.9.1.min.js"></script> 
    <script src="<?=MEDIA_URL ?>js/sliderh/owl.carousel.js"></script>

    <script>
    $(document).ready(function() {
      $("#owl-demo").owlCarousel({
        autoPlay: 3000,
       items :3,
        itemsDesktop : [1199,3],
        itemsDesktopSmall : [979,3]
      });

    });
    </script>
<div class="content960">
          <div class="col2 align-left"><div id="map_canvas"></div><br />
            </div>
          	
            <div class="col2 col470 align-right">
               	<div class="subtitle2">
                    <a href="<?= $this->magasinInfo['liengmap'];?>" target="_blank">
                        PLAN INTERACTIF 
                    </a>                		
       		  </div>
            <div class="col21">
            <p><?= $this->magasinInfo['adresse'];?></p><br />
            <p><strong>Coordonnées GPS :</strong></p>
            <p> Latitude : <?= $this->magasinInfo['latitude'];?></p>
            <p> Longitude : <?= $this->magasinInfo['longitude'];?> </p></div>
                <div class="col230">
             
                    <p><strong>Gérant : <?= $this->magasinInfo['gerant'];?></strong></p>
                    <p>Tél. : <?= $this->magasinInfo['tel'];?></p>
                    <p>Fax : <?= $this->magasinInfo['fax'];?> </p>
                    <h3>HORAIRES D'OUVERTURE</h3>
                    <p><?= $this->magasinInfo['horaires'];?></p><? $emailmagasin = $this->magasinInfo['email'];?>
                    
                </div>
                
			  <div class="subtitle3">
                	<div class="icontitle icon-contact"><? $telp = str_replace(" ", "", $this->magasinInfo['tel']);?><a href="tel:<? echo $telp;?>">APPELER LE MAGASIN</a></div>
              </div>
              <div class="subtitle3">
                	<div class="icontitle icon-envoyer"><a href="/contact"  class="btn-smart" >ENVOYER UN MAIL</a><a href="#" onClick="magasinpopup();" class="btn-ipad" >ENVOYER UN MAIL</a></div>
                 </div>
              
            
                      
                
            </div>
            
            
            </div>
            
            
            
          </div>
          
          
          
         
          </div>
          
          
          
          
                   <!-- // actualite // -->
        <!-- <div id="maga-actualite">
         <div id="actualite">
           		<h2>L’ACTUALITÉ MOTO EXPERT METZ</h2>
            <div class="actualite-col3   actualite-col1"><img src="<?=MEDIA_URL ?>images/solde.jpg" width="87" height="87" /><h3>Vive les Soldes d’hiver pour s’équiper pas cher !</h3><p>Elles débuteront dans votre magasin Moto Expert officiellement le mercredi 11 janvier 2012 à 8 heures</p></div>
                <div class="actualite-col3 actualite-col2"><img src="<?=MEDIA_URL ?>images/people.jpg" width="87" height="87" /><h3>Rejoingnez le Fan Club et bénéficiez du prix Fan* -6% immédiatement !</h3><p>Rejoingnez le Fan Club et bénéficiez du prix Fan* -6% immédiatement !</p></div>
                <div class="actualite-col3right"><img src="<?=MEDIA_URL ?>images/house.jpg" width="87" height="87" /><h3>Fermeture du magasin de Saint-Quentin</h3><p>Le magasin est dorénavant fermé. Nous vous informerons dès sa réouverture.</p></div>
                
          </div>  
       </div>

    <a href="#" class="block-link-maga">› VOIR TOUTES LES ACTUALITES</a>-->     
      
      	<div id="ye-content">
        <!-- / top bottom /-->
        <div  class="ye-top"><img src="<?=MEDIA_URL ?>images/top.png" width="47" height="45"></div>
            <div class="ye-botton"><img src="<?=MEDIA_URL ?>images/botton.png" width="47" height="45"></div>
                <!-- / top bottom /-->
            <div class="ye-contnt-b">
                <div id="ye-top">
                        <h2>NOS OCCASIONS <br />MOTO </h2>
                        <div class="ye-right"><strong>› <?= $this->countMagasin['total'];?> annonce moto</strong></div>
                </div>
                <div id="results-content">
                    <div id="list_">
                    </div>
                <?php
                $config = Zend_Registry::get('config');
                $i = 0;
                foreach ($this->lastAnnoncesMagasin as $anuncionsTienda) :
                    $i++;
                    $foto = str_replace(",",".",$anuncionsTienda['nom_fichier']);    
                    $ruta = $config->app->photoUrl. $anuncionsTienda['departement'].'/'.$foto;
                   
                    if(count($this->lastAnnoncesMagasin)-1 == $i-1){
                        $class = "result-col3 col3no no-bor-bot";
                    }else{
                        $class = "result-col3 no-bor-bot";
                    }
                    
                ?>
               
                <div class="<?= $class;?>">                        
                        <div class="result-imgs">
                            <a href="Fiche-Moto/index/id/<?php echo $anuncionsTienda['id'];?>">
                                <img src="<?=$ruta;?>" width="300" />
                            </a>
                        </div>
                        <div class="result-price-w"><?=($anuncionsTienda['prix'] > 0) ? $anuncionsTienda['prix'].' €' : 'A débattre' ;?></div>
                        <div class="result-desc">
                        <div class="result-date"><?php echo date('d/m/Y', $this->detailAnnonces['date'])?> </div>
                            <p><strong><?= $anuncionsTienda['titre'];?></strong><br />
                       <?php echo $anuncionsTienda['marque']. " " . $anuncionsTienda['modele'] . " " . 
                               $anuncionsTienda['cylindree']. " cm3 " . $anuncionsTienda['km']. " km" . 
                               " Année " . $anuncionsTienda['annee']?></p>
                        <?php if ($anuncionsTienda['controle']==1){?>
                        <span class="visuel">CONTRÛLE VISUEL</span>
                        <?php }?>
                        <?php if ($anuncionsTienda['isgarantie']==1){?>
                        <span class="garantie">GARANTIE </span>
                        <?php }?>    
                        </div>

                    </div>
                <?php endforeach;?>
                <!--<div class="result-col3 no-bor-bot">            
                    <div class="result-imgs"><img src="<?=MEDIA_URL ?>images/resutats-img.jpg" width="300" height="115" /></div>
                    <div class="result-price-w">4200  € </div>
                        <div class="result-desc">
                        <div class="result-date">05/02114 </div>
                            <p><strong>Suzuki RMZ 250</strong><br />
                        Honda - CB 600 F ABS - 600 cm3 - 15550 km Année 2005 - à débattre</p>
                        <a href="#" class="visuel">CONTRÛLE VISUEL</a> <a href="#" class="garantie">GARANTIE </a>
                        </div>

                </div>
                <div class="result-col3 col3no no-bor-bot">
                    <div class="result-imgs"><img src="<?=MEDIA_URL ?>images/resutats-img.jpg" width="300" height="115" /></div>
                        <div class="result-price-w">4200  € </div>
                    <div class="result-desc">
                    <div class="result-date">05/02114 </div>
                        <p><strong>Suzuki RMZ 250</strong><br />
                    Honda - CB 600 F ABS - 600 cm3 - 15550 km Année 2005 - à débattre</p>
                    <a href="#" class="visuel">CONTRÛLE VISUEL</a> <a href="#" class="garantie">GARANTIE </a>
                    </div>
                </div>-->
            </div>     
        </div>

    </div>
<a href="/annonces?magasin=<?= $this->magasinInfo['id_me'];?>" class="block-link-maga btnfoo">› VOIR TOUTES LES OCCASIONS DU MAGASIN </a><br ><br/>

<!--/*********************************************************/--> 

<div id="my_contact_magasin" class="contact"> 
  <div id="wrapper-form">
    	<div id="new-form">
        	<div id="new-navigation"><a href="#" class="new-prev" onClick="jQuery('#my_contact_magasin').trigger('close');">RETOUR</a>
        	<p>  </p> </div>
 <script>
				 function validate(){
				   
				  if (document.formmagasin.email.value == ""&&document.formmagasin.ville.value == ""&&document.formmagasin.code_postal.value == ""&&document.formmagasin.adresse.value == ""&&document.formmagasin.prenom.value == ""&&document.formmagasin.nom.value == ""){ 
				   jQuery('#formmagasin #email').addClass( 'error' );  				   
				   jQuery('#formmagasin #emaillabel').addClass( 'error' );
				   jQuery('#formmagasin #emaillabel').removeClass( 'nodisplay');	
				   jQuery('#formmagasin #ville').addClass( 'error' );  				   
				   jQuery('#formmagasin #villelabel').addClass( 'error' );
				   jQuery('#formmagasin #villelabel').removeClass( 'nodisplay');	
				   jQuery('#formmagasin #code_postal').addClass( 'error' );  				   
				   jQuery('#formmagasin #code_postallabel').addClass( 'error' );
				   jQuery('#formmagasin #code_postallabel').removeClass( 'nodisplay');
				   jQuery('#formmagasin #adresse').addClass( 'error' );  				   
				   jQuery('#formmagasin #adresselabel').addClass( 'error' );
				   jQuery('#formmagasin #adresselabel').removeClass( 'nodisplay');
				   jQuery('#formmagasin #prenom').addClass( 'error' );  				   
				   jQuery('#formmagasin #prenomlabel').addClass( 'error' );
				   jQuery('#formmagasin #prenomlabel').removeClass( 'nodisplay');	
				   jQuery('#formmagasin #nom').addClass( 'error' );  				   
				   jQuery('#formmagasin #nomlabel').addClass( 'error' );
				   jQuery('#formmagasin #nomlabel').removeClass( 'nodisplay');
				   			
					return false; 
				  }
				  
				  if (document.formmagasin.nom.value == ""){ 
				   jQuery('#formmagasin #nom').addClass( 'error' );  				   
				   jQuery('#formmagasin #nomlabel').addClass( 'error' );
				   jQuery('#formmagasin #nomlabel').removeClass( 'nodisplay');				
					return false; 
				  }
				  if (document.formmagasin.prenom.value == ""){ 
				   jQuery('#formmagasin #prenom').addClass( 'error' );  				   
				   jQuery('#formmagasin #prenomlabel').addClass( 'error' );
				   jQuery('#formmagasin #prenomlabel').removeClass( 'nodisplay');				
					return false; 
				  }
				  if (document.formmagasin.adresse.value == ""){ 
				   jQuery('#formmagasin #adresse').addClass( 'error' );  				   
				   jQuery('#formmagasin #adresselabel').addClass( 'error' );
				   jQuery('#formmagasin #adresselabel').removeClass( 'nodisplay');				
					return false; 
				  } 
				  if (document.formmagasin.code_postal.value == ""){ 
				   jQuery('#formmagasin #code_postal').addClass( 'error' );  				   
				   jQuery('#formmagasin #code_postallabel').addClass( 'error' );
				   jQuery('#formmagasin #code_postallabel').removeClass( 'nodisplay');				
					return false; 
				  }
				  if (document.formmagasin.ville.value == ""){ 
				   jQuery('#formmagasin #ville').addClass( 'error' );  				   
				   jQuery('#formmagasin #villelabel').addClass( 'error' );
				   jQuery('#formmagasin #villelabel').removeClass( 'nodisplay');				
					return false; 
				  } 
				   if (document.formmagasin.email.value == ""){ 
				   jQuery('#formmagasin #email').addClass( 'error' );  				   
				   jQuery('#formmagasin #emaillabel').addClass( 'error' );
				   jQuery('#formmagasin #emaillabel').removeClass( 'nodisplay');				
					return false; 
				  }        
				return true;
				}
              /*************************************************/
				 function validacion(){

				  if (document.formmagasin.nom.value!= ""){ 
				   jQuery('#formmagasin #nom').removeClass( 'error' ); 				   
				   jQuery('#formmagasin #nomlabel').removeClass( 'error' );
				   jQuery('#formmagasin #nomlabel').addClass( 'nodisplay');				
				 
				  } 
				  if (document.formmagasin.prenom.value!= ""){ 
				   jQuery('#formmagasin #prenom').removeClass( 'error' ); 				   
				   jQuery('#formmagasin #prenomlabel').removeClass( 'error' );
				   jQuery('#formmagasin #prenomlabel').addClass( 'nodisplay');				
				
				  }
				  if (document.formmagasin.adresse.value!= ""){ 
				   jQuery('#formmagasin #adresse').removeClass( 'error' ); 				   
				   jQuery('#formmagasin #adresselabel').removeClass( 'error' );
				   jQuery('#formmagasin #adresselabel').addClass( 'nodisplay');				
				
				  }
				  if (document.formmagasin.code_postal.value!= ""){ 
				   jQuery('#formmagasin #code_postal').removeClass( 'error' ); 				   
				   jQuery('#formmagasin #code_postallabel').removeClass( 'error' );
				   jQuery('#formmagasin #code_postallabel').addClass( 'nodisplay');				
				
				  }
				  if (document.formmagasin.ville.value!= ""){ 
				   jQuery('#formmagasin #ville').removeClass( 'error' ); 				   
				   jQuery('#formmagasin #villelabel').removeClass( 'error' );
				   jQuery('#formmagasin #villelabel').addClass( 'nodisplay');				
				 
				  }
				if (document.formmagasin.email.value!= ""){ 
				   jQuery('#formmagasin #email').removeClass( 'error' ); 				   
				   jQuery('#formmagasin #emaillabel').removeClass( 'error' );
				   jQuery('#formmagasin #emaillabel').addClass( 'nodisplay');				
			
				  }
				  
				   
				  
				}   
        </script> 
                  
            <form name="formmagasin"  class="cmxform"  id="formmagasin" method="post" action="/magasin/mail/magasin/<?=$this->magasinInfo['id_me'];?>"  onSubmit="return validate()">
        <p><?php echo ($this->error)?"S'il vous plaît vérifier vos informations":''?></p>

<p><input name="nom" id="nom" type="text" placeholder="Nom" value="<?php echo ($nom)?$datos["nom"]:'';?>" onKeyPress="validacion()"  />
<label for="nom" id="nomlabel" class="nodisplay">Veuillez renseigner le champ nom</label>
</p>
<p><input name="prenom" id="prenom" type="text" placeholder="Prénom" value="<?php echo ($prenom)?$datos["prenom"]:'';?>" onKeyPress="validacion()" />
<label for="prenom"  id="prenomlabel" class="nodisplay">Veuillez renseigner le champ prenom</label>
</p>
<p><input name="adresse" id="adresse" type="text" placeholder="Adresse"  value="<?php echo ($adresse)?$datos["adresse"]:'';?>"  onKeyPress="validacion()" />
 <label for="adresse" id="adresselabel" class="nodisplay">Veuillez renseigner votre adresse</label>
</p>
<p><input name="code_postal" id="code_postal" type="text" placeholder="Code Postal"  value="<?php echo ($code_postal)?$datos["code_postal"]:'';?>" onKeyPress="validacion()" />
<label for="code_postal" id="code_postallabel"  class="nodisplay">Veuillez renseigner votre code postal</label>
</p>
<p><input name="ville" id="ville" type="text" placeholder="Ville" value="<?php echo ($ville)?$datos["ville"]:'';?>"  onKeyPress="validacion()" />
<label for="ville" id="villelabel"  class="nodisplay">Veuillez renseigner votre ville</label>
</p>
          <p><input name="telephone"  id="telephone" type="text" placeholder="Téléphone"></p>

            <p>
            <input name="email" id="email" type="text" placeholder="Votre adresse Email" value="<?php echo ($email)?$datos["email"]:'';?>"  onKeyPress="validacion()">
            <label for="email" id="emaillabel"  class="nodisplay">Veuillez renseigner votre email</label>
            
            <input name="mailTienda" type="hidden" value="<?php echo $this->magasinInfo["email"];?>">
            <input name="idTienda" type="hidden" value="<?php echo $this->magasinInfo["id_me"];?>">
            </p>
<p> 
<?= $this->formMagasin->magasin?>

</p>

<p> <textarea name="message" id="message" cols="45" rows="5">message</textarea></p>
<p></p><p></p>
               <div class="fomrinfo">
                    	<span>Veuillez saisir les lettres de limage dans le champ situé sous l'image en respectant les majuscules et les minuscules.</span>
                    <div class="captcha">
                    	<div class="imgcap"><img src="<?=MEDIA_URL ?>CaptchaSecurityImages.php" /></div>
                        <div class="inpcap"><input name="" type="text"></div>
                    </div>
                   <div class="condition">
                   	<input name="" type="checkbox" value="" />En cochant cette case, je souhaite recevoir la newsletter Moto Expert
                   
                   </div>
                    
                    <input name="ENVOYER" type="submit" id="ENVOYER" value="ENVOYER" />
                    
                    </div>
<p></p>

          

            
        </form>
    	</div>
	  
      
	</div>
   </div>
<!--/*********************************************************/-->  
   <script>
    var magasinpopup = function(){  
    jQuery('#my_contact_magasin').lightbox_me({
      centered: true,
      onLoad: function() {
    	  jQuery('#my_contact_magasin_text').html("Stuff");
      }
    });
  }
</script>       
